import { ACTIONS } from "@/lib/auth/permissions";

/**
 * Nomes que o Estúdio grava no audit_log (sufixo `.denied` opcional). O banco aceita só esta
 * lista (`studio_audit_actions()`, migration 0025); o teste de integração confere as duas.
 */
export const AUDIT_ACTIONS = [
  ...ACTIONS,
  "article.assign",
  "article.reject",
  "article.reprocess",
  "article.request_changes",
  "article.request_review",
  "article.save",
  "article.sources",
  "article.suggestion.accept",
  "article.suggestion.reject",
  "article.update",
  "correction.open",
  "correction.publish",
  "event.approve",
  "event.reject",
  "media.block",
  "media.generate",
  "media.license.block",
  "media.license.renew",
  "media.replace",
  "media.takedown.request",
  "report.respond",
  "media.image_text",
  "approval.request",
  "approval.approve",
  "approval.reject",
  "pipeline.reprocess",
  "pipeline.run_now",
  "source.analyze",
  "source.test_connection",
  "source.collect_now",
  "source.approval_requested",
  "source.approval_applied",
  "prompt.create",
  "prompt.rollback",
  "prompt.playground",
  "agent.toggle",
  "ads.campaign.save",
  "ads.campaign.toggle",
  "ads.flag.toggle",
  "push.send",
  "settings.update",
  "security.clear_login_blocks",
  // Administração de usuários, equipes, taxonomia e home (P5-T8; migration 0035, admin_audit_actions).
  "taxonomy.manage",
  "home.manage",
  "user.invite",
  "user.invite_revoke",
  "role.grant",
  "role.revoke",
  "role.sections",
  "role.admin_request",
  "team.save",
  "team.delete",
  "team.member_add",
  "team.member_remove",
  "tag.create",
  "tag.rename",
  "tag.merge",
  "tag.delete",
  "section.rename",
  "section.create",
  "home.save_draft",
  "home.publish",
  "flag.set",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
