import type { HomeModuleKey } from "@/lib/home/modules";

/** Textos da Administração (usuários, papéis, equipes, taxonomia e home; P5-T8). */
export const ADMIN_TEXT = {
  nav: {
    group: "Administração",
    overview: "Painel",
    users: "Usuários",
    roles: "Papéis",
    teams: "Equipes",
    taxonomy: "Taxonomia",
    home: "Home",
  },
  loading: "Carregando a administração",
  errorTitle: "Não foi possível carregar esta tela",
  errorBody: "O banco não respondeu agora. Nada foi alterado. Tente de novo em instantes.",
  retry: "Tentar de novo",
  forbidden: "Seu papel não permite esta ação.",
  invalid: "Confira os campos e tente de novo.",
  notFound: "Não encontramos o que você pediu. Atualize a página.",
  saved: "Alteração salva.",
} as const;

export const ADMIN_OVERVIEW = {
  title: "Administração",
  intro:
    "Pessoas, papéis, equipes, taxonomia e a home do portal. Toda alteração fica na auditoria.",
  cards: [
    { href: "/estudio/admin/usuarios", title: "Usuários", text: "Convidar e ver quem tem acesso." },
    {
      href: "/estudio/admin/papeis",
      title: "Papéis e seções",
      text: "Conceder e revogar papéis. Administração pede aprovação de outra pessoa.",
    },
    { href: "/estudio/admin/equipes", title: "Equipes", text: "Agrupar a redação por equipe." },
    {
      href: "/estudio/admin/taxonomia",
      title: "Taxonomia",
      text: "Editorias, tags e mesclagem de tags duplicadas.",
    },
    {
      href: "/estudio/admin/home",
      title: "Home e módulos",
      text: "Ordem dos blocos da página inicial, com publicação.",
    },
  ],
  countUsers: (n: number) => `${n} ${n === 1 ? "pessoa com acesso" : "pessoas com acesso"}`,
  countInvites: (n: number) => `${n} ${n === 1 ? "convite pendente" : "convites pendentes"}`,
  countApprovals: (n: number) =>
    `${n} ${n === 1 ? "aprovação de papel esperando" : "aprovações de papel esperando"}`,
} as const;

export const USERS_TEXT = {
  title: "Usuários",
  intro:
    "Quem tem acesso ao Estúdio. Convidar envia um link por e-mail; o convite fica pendente até a pessoa aceitar.",
  inviteTitle: "Convidar pessoa",
  email: "E-mail",
  emailHint: "Exemplo: ana@exemplo.com",
  role: "Papel inicial",
  sections: "Editorias (separe por vírgula, para editor)",
  invite: "Enviar convite",
  invited: "Convite enviado. Ele fica como pendente até a pessoa aceitar.",
  invitedNote:
    "O envio real de e-mail depende do provedor de SMTP (pendência B-005): o convite já está registrado e o link aparece no registro da fila.",
  revoked: "Convite cancelado.",
  peopleTitle: "Pessoas com acesso",
  peopleCaption: "Pessoas com acesso ao Estúdio",
  colName: "Nome",
  colEmail: "E-mail",
  colRoles: "Papéis",
  colLastAccess: "Último acesso",
  never: "Ainda não entrou",
  noRoles: "Sem papel",
  invitesTitle: "Convites",
  invitesCaption: "Convites de equipe",
  colInvitedRole: "Papel",
  colInvitedAt: "Enviado em",
  colStatus: "Situação",
  pending: "Convite pendente",
  revoke: "Cancelar convite",
  revokeNamed: (email: string) => `Cancelar convite de ${email}`,
  noInvites: "Nenhum convite pendente.",
  emptyTitle: "Ninguém com acesso ainda",
  emptyBody: "Convide a primeira pessoa acima.",
  inviteAdminNote:
    "Convite nunca concede administração; isso só pelo pedido de aprovação em Papéis.",
  errors: {
    already: "Essa pessoa já tem acesso.",
    duplicate: "Já existe um convite pendente para este e-mail.",
    email: "Escreva um e-mail válido. Exemplo: ana@exemplo.com",
    role: "Escolha um papel que não seja administração.",
  },
  mailSubject: "Convite para a equipe do CityNews Cuiabá",
  mailBody: (link: string) =>
    `Você foi convidado para a equipe do CityNews Cuiabá. Para aceitar, abra este link em até 7 dias: ${link}`,
} as const;

export const ROLES_TEXT = {
  title: "Papéis e permissões",
  intro:
    "Conceda ou revogue papéis e defina as editorias de cada pessoa. Conceder administração pede a aprovação de outra pessoa.",
  personCaption: "Papéis por pessoa",
  colPerson: "Pessoa",
  colRoles: "Papéis e editorias",
  colActions: "Alterar",
  grantTitle: "Conceder papel",
  person: "Pessoa",
  role: "Papel",
  sections: "Editorias (separe por vírgula)",
  justification: "Justificativa (obrigatória para administração)",
  grant: "Conceder papel",
  revoke: "Revogar",
  revokeNamed: (who: string, role: string) => `Revogar ${role} de ${who}`,
  saveSections: "Salvar editorias",
  sectionsNamed: (who: string, role: string) => `Editorias de ${who} como ${role}`,
  saveSectionsNamed: (who: string, role: string) => `Salvar editorias de ${who} como ${role}`,
  granted: "Papel concedido.",
  requested:
    "Pedido de aprovação enviado. A aprovação precisa ser de outra pessoa; o papel de administração só vale depois dela.",
  waiting:
    "Já existe um pedido de administração para esta pessoa esperando decisão. Acompanhe em Aprovações.",
  revokedDone: "Papel revogado.",
  sectionsDone: "Editorias salvas.",
  approvalsLink: "Abrir Aprovações",
  historyTitle: "Histórico de alterações",
  historyCaption: "Últimas alterações de papéis",
  colWhen: "Quando",
  colWho: "Feito por",
  colWhat: "O quê",
  noHistory: "Nenhuma alteração registrada ainda.",
  errors: {
    self: "Ninguém altera o próprio papel. Peça a outra pessoa da administração.",
    lastAdmin: "O último administrador não pode ser removido.",
    justification: "Escreva a justificativa do pedido de administração.",
    person: "Escolha uma pessoa.",
    unknownSection: "Alguma editoria não existe. Use os nomes da taxonomia.",
    approval: "O pedido de aprovação não foi aceito. Confira a pessoa e a justificativa.",
    twoPerson: "A concessão de administração exige aprovação de outra pessoa.",
  },
  history: {
    "role.grant": "Concedeu papel",
    "role.revoke": "Revogou papel",
    "role.sections": "Alterou editorias",
    "user.invite": "Convidou",
    "user.invite_revoke": "Cancelou convite",
  } as Record<string, string>,
} as const;

export const TEAMS_TEXT = {
  title: "Equipes",
  intro: "Agrupe a redação por equipe. Uma pessoa pode estar em mais de uma.",
  createTitle: "Nova equipe",
  name: "Nome da equipe",
  description: "Descrição (opcional)",
  lead: "Responsável",
  noLead: "Sem responsável",
  create: "Criar equipe",
  save: "Salvar equipe",
  saveNamed: (n: string) => `Salvar equipe ${n}`,
  del: "Excluir equipe",
  delNamed: (n: string) => `Excluir equipe ${n}`,
  addMember: "Adicionar à equipe",
  member: "Pessoa",
  removeNamed: (who: string, team: string) => `Remover ${who} da equipe ${team}`,
  remove: "Remover",
  members: (n: number) => `${n} ${n === 1 ? "integrante" : "integrantes"}`,
  noMembers: "Sem integrantes.",
  emptyTitle: "Nenhuma equipe ainda",
  emptyBody: "Crie a primeira equipe acima.",
  created: "Equipe criada.",
  updated: "Equipe salva.",
  deleted: "Equipe excluída.",
  added: "Pessoa adicionada.",
  removed: "Pessoa removida da equipe.",
  errors: {
    duplicate: "Já existe uma equipe com esse nome.",
    name: "Escreva um nome de 2 a 80 caracteres.",
  },
} as const;

export const TAXONOMY_TEXT = {
  title: "Taxonomia",
  intro:
    "Editorias, tags e a mesclagem de tags duplicadas. Mesclar preserva os vínculos: as matérias passam para a tag que fica.",
  sectionsTitle: "Editorias",
  sectionsCaption: "Editorias e subeditorias",
  colSlug: "Endereço",
  colName: "Nome",
  colParent: "Dentro de",
  colAutonomy: "Categoria de autonomia",
  top: "Editoria principal",
  renameNamed: (n: string) => `Novo nome da editoria ${n}`,
  saveNamed: (n: string) => `Salvar nome da editoria ${n}`,
  save: "Salvar nome",
  newSectionTitle: "Nova subeditoria",
  newSectionName: "Nome da subeditoria",
  newSectionParent: "Dentro de",
  newSection: "Criar subeditoria",
  sectionSaved: "Nome da editoria salvo.",
  sectionCreated: "Subeditoria criada.",
  tagsTitle: "Tags",
  tagsCaption: "Tags e quantidade de matérias",
  colTag: "Tag",
  colArticles: "Matérias",
  colActions: "Alterar",
  newTag: "Nova tag",
  newTagName: "Nome da tag",
  createTag: "Criar tag",
  tagCreated: "Tag criada.",
  tagRenamed: "Tag renomeada.",
  tagDeleted: "Tag excluída.",
  tagMerged: (n: number) =>
    `Tags mescladas. ${n} ${n === 1 ? "vínculo preservado" : "vínculos preservados"}.`,
  delete: "Excluir",
  deleteNamed: (n: string) => `Excluir a tag ${n}`,
  deleteBlocked: "Só tags sem matérias podem ser excluídas.",
  emptyTags: "Nenhuma tag ainda. Crie a primeira acima.",
  duplicatesTitle: "Sugestões de tags duplicadas",
  duplicatesIntro:
    "Sugestão automática por nome parecido (sem acento, caixa ou plural). Você decide se mescla.",
  noDuplicates: "Nenhuma tag duplicada encontrada.",
  mergeInto: (name: string) => `Mesclar em ${name}`,
  mergeNamed: (from: string, into: string) => `Mesclar a tag ${from} na tag ${into}`,
  mergeTitle: "Mesclar tags manualmente",
  mergeFrom: "Tag que sai",
  mergeTo: "Tag que fica",
  merge: "Mesclar tags",
  placesTitle: "Bairros e municípios",
  placesIntro:
    "Lista de referência do portal, mantida no código (src/content/pt-BR/neighborhoods.ts). A edição por esta tela fica para depois.",
  places: (n: number) => `${n} bairros de Cuiabá e da região`,
  errors: {
    duplicate: "Já existe uma tag com esse nome ou endereço.",
    name: "Escreva um nome de 2 a 60 caracteres.",
    same: "Escolha duas tags diferentes.",
    notEmpty: "A tag ainda tem matérias. Mescle em outra antes de excluir.",
  },
} as const;

export const HOME_ADMIN_TEXT = {
  title: "Home e módulos",
  intro:
    "Ordem e presença dos blocos da página inicial. A manchete, o Agora e a barra de urgente são fixos. A home pública lê a versão publicada.",
  fixed: "Fixos no topo: barra de urgente, manchete e Agora.",
  listLabel: "Módulos da home, em ordem",
  keyboardHelp:
    "Para mudar a ordem pelo teclado, foque o módulo e use Alt + seta para cima ou Alt + seta para baixo.",
  moveUp: (n: string) => `Subir ${n}`,
  moveDown: (n: string) => `Descer ${n}`,
  show: (n: string) => `Mostrar ${n} na home`,
  position: (i: number, total: number) => `posição ${i} de ${total}`,
  moved: (name: string, i: number, total: number) =>
    `${name} movido para a posição ${i} de ${total}.`,
  saveDraft: "Salvar rascunho",
  publish: "Publicar na home",
  reset: "Voltar ao layout padrão",
  draftSaved: "Rascunho salvo. A home pública ainda mostra a versão publicada.",
  published: (v: number) => `Versão ${v} publicada. A home já usa a nova ordem.`,
  status: {
    published: (v: number) => `Versão publicada: ${v}.`,
    draft: "Você está vendo um rascunho ainda não publicado.",
    none: "Ainda não há versão publicada: a home usa o layout padrão.",
  },
  saving: "Salvando",
  error: "Não foi possível salvar agora. Tente de novo.",
  modules: {
    topics: { name: "Assuntos em andamento", text: "Três assuntos com cobertura acumulada." },
    collections: { name: "Coleções", text: "Coleções editoriais em destaque." },
    nearby: { name: "Perto de você", text: "Convite para ver notícias do bairro." },
    agenda_services: { name: "Agenda e serviços", text: "Próximos eventos e atalhos de serviço." },
    sections: { name: "Blocos de editoria", text: "Política, Economia e Cultura." },
    most_read: { name: "Mais lidas", text: "As matérias mais lidas do dia." },
    sources: { name: "Fontes em destaque", text: "Fontes locais para seguir." },
    aggregated: { name: "Veja também em outros portais", text: "Panorama de fontes, com origem." },
    newsletter: { name: "Newsletter", text: "Formulário de inscrição." },
  } satisfies Record<HomeModuleKey, { name: string; text: string }>,
} as const;
