/** Textos da Administração, parte 2 (A07, A08, A10–A14, P5-T9). */

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const CAMPAIGN_STATUS_LABEL = {
  draft: "Rascunho",
  active: "Ativa",
  paused: "Pausada",
  ended: "Encerrada",
} as const;

export const PRIVACY_KIND_LABEL = {
  access: "Acesso aos dados",
  delete: "Exclusão",
  rectify: "Correção",
  portability: "Portabilidade",
} as const;

export const PRIVACY_STATUS_LABEL = {
  open: "Aberto",
  in_progress: "Em andamento",
  done: "Concluído",
  rejected: "Recusado",
} as const;

export const ADMIN_OPS_TEXT = {
  ads: {
    title: "Publicidade e patrocinados",
    intro:
      "Campanhas de conteúdo patrocinado: anunciante, período, peça, editorias permitidas e entregas. As regras abaixo são fixas e valem para toda campanha.",
    rulesTitle: "Regras fixas",
    rules: [
      "Rótulo PATROCINADO sempre visível, nunca só por cor.",
      "No máximo 1 patrocinado a cada 6 cards; nunca na manchete nem na primeira dobra.",
      "Nunca em Política, Segurança ou Saúde, nem nas respostas do Pergunte ao CityNews.",
      "Nunca ao lado de matéria urgente nem de contexto sensível (crime, tragédia, saúde individual).",
      "Patrocinado não conta como matéria editorial nem entra no sitemap de notícias.",
    ],
    create: "Nova campanha",
    table: "Campanhas",
    col: {
      advertiser: "Anunciante",
      period: "Período",
      sections: "Editorias",
      status: "Situação",
      deliveries: "Entregas",
    },
    empty: "Nenhuma campanha cadastrada.",
    preview: "Pré-visualização com selo",
    dialog: {
      titleNew: "Nova campanha",
      titleEdit: (name: string) => `Editar campanha de ${name}`,
      advertiser: "Anunciante",
      startsOn: "Início",
      endsOn: "Fim",
      creativeTitle: "Título da peça",
      creativeHref: "Link da peça",
      creativeImage: "Imagem (URL, opcional)",
      creativeAlt: "Texto alternativo da imagem",
      sections: "Editorias permitidas",
      status: "Situação",
      submit: "Salvar campanha",
      remove: "Apagar campanha",
      saved: (name: string) => `Campanha de ${name} salva.`,
      removed: "Campanha apagada.",
      forbiddenSection: "Política, Segurança e Saúde nunca recebem patrocinado.",
      period: "O fim precisa ser igual ou depois do início.",
    },
  },
  seo: {
    title: "SEO",
    intro:
      "Modelo de título, sitemaps, robots, redirecionamentos de endereços antigos, dados estruturados e verificação de páginas sem meta description.",
    titleTemplate: "Modelo de título",
    titleTemplateHint:
      "Use {title} no lugar do título da página. Exemplo: “{title} · CityNews Cuiabá”.",
    titleTemplateSave: "Salvar modelo",
    titleTemplateSaved: "Modelo de título salvo.",
    titleTemplateInvalid: "O modelo precisa conter {title} e ter até 120 caracteres.",
    sitemaps: "Sitemaps",
    sitemapsIntro: "Índice e sitemaps por tipo, gerados pelo portal (cache de 5 minutos).",
    robots: "robots.txt",
    robotsIntro:
      "Portal aberto; Estúdio, API, busca, Pergunte e telas de conta ficam fora do índice.",
    structured: "Dados estruturados",
    structuredIntro: "JSON-LD gerado pelo portal.",
    structuredTypes: [
      "NewsArticle em cada matéria (autor, fontes, datas, correção)",
      "Organization e WebSite (com busca) na home",
      "BreadcrumbList nas matérias e editorias",
      "Event na agenda",
    ],
    missing: "Matérias publicadas sem meta description",
    missingIntro:
      "Publicadas sem `seo_description`: o checklist bloqueia novas, estas vieram antes ou do pipeline.",
    missingEmpty: "Todas as matérias publicadas têm meta description.",
    missingCount: (n: number) => `${n} ${plural(n, "matéria", "matérias")}`,
    edit: "Editar",
    redirects: "Redirecionamentos",
    redirectsIntro:
      "Endereço antigo (matéria arquivada, editoria renomeada) → destino. Só caminhos internos.",
    redirectsTable: "Redirecionamentos",
    col: { from: "De", to: "Para", kind: "Tipo", reason: "Motivo", when: "Quando" },
    redirectsEmpty: "Nenhum redirecionamento.",
    addRedirect: "Novo redirecionamento",
    remove: "Apagar",
    dialog: {
      title: "Novo redirecionamento",
      from: "Endereço antigo",
      to: "Destino",
      kind: "Tipo",
      permanent: "301 (permanente)",
      temporary: "302 (temporário)",
      reason: "Motivo",
      submit: "Criar",
      saved: (from: string, to: string) => `${from} agora leva para ${to}.`,
      removed: "Redirecionamento apagado.",
      errors: {
        invalid_from:
          "O endereço antigo precisa começar com / e não ter espaços. Exemplo: /materia/titulo-antigo",
        invalid_to: "O destino precisa ser um caminho interno. Exemplo: /materia/titulo-novo",
        same: "Origem e destino são iguais.",
        loop: "Esse destino voltaria para a origem (laço).",
        exists: "Já existe um redirecionamento para este endereço.",
      },
    },
  },
  audit: {
    title: "Auditoria",
    intro:
      "Quem fez o quê, quando e em qual objeto. Registro só de acréscimo: nada aqui é editado ou apagado. IPs aparecem mascarados para quem não é da administração.",
    filters: "Filtros",
    actor: "Quem (nome ou id)",
    action: "Ação",
    object: "Objeto",
    from: "De (data)",
    to: "Até (data)",
    apply: "Filtrar",
    clear: "Limpar",
    table: "Registros de auditoria",
    col: {
      when: "Quando",
      who: "Quem",
      action: "Ação",
      object: "Objeto",
      details: "Detalhes",
      ip: "IP (hash)",
    },
    count: (n: number, more: boolean) =>
      `${more ? "mais de " : ""}${n} ${plural(n, "registro", "registros")}`,
    masked: "IPs mascarados",
    export: "Exportar CSV",
    exportNote:
      "Até 5000 linhas, sem nome nem e-mail e com ator pseudonimizado fora da administração. Se passar do limite, a última linha do arquivo avisa.",
    empty: "Nenhum registro com estes filtros.",
    more: "Carregar mais antigos",
    details: "Ver detalhes",
  },
  security: {
    title: "Segurança e privacidade",
    intro:
      "Segundo fator da equipe, sessões, retenção, pedidos LGPD com prazo, revisão de acessos e rotação de chaves. Valores de chave nunca ficam no banco.",
    settings: "Políticas",
    require2fa: "Exigir segundo fator (2FA) da equipe",
    require2faNotApplied:
      "Ainda não aplicado: o Estúdio não tem cadastro de segundo fator, então a exigência fica desligada. A coluna 2FA da revisão de acessos mostra quem já cadastrou no Supabase.",
    sessionHours: "Duração máxima da sessão (horas)",
    sessionHoursHint:
      "Aplicado: passado esse tempo desde a última entrada, a pessoa da equipe entra de novo.",
    retentionDays: "Retenção de eventos individuais (dias, de 30 a 90)",
    retentionDaysHint:
      "Aplicado toda madrugada: depois disso o evento perde o que identifica o leitor. Teto de 90 dias (spec §10).",
    save: "Salvar políticas",
    saved: "Políticas salvas.",
    privacy: "Pedidos LGPD",
    privacyIntro:
      "Prazo de 15 dias a partir do pedido. Registre aqui o que chega por e-mail ou pelo formulário.",
    privacyTable: "Pedidos LGPD",
    privacyCol: { kind: "Tipo", email: "E-mail", status: "Situação", due: "Prazo", notes: "Notas" },
    privacyEmpty: "Nenhum pedido aberto.",
    newRequest: "Registrar pedido",
    overdue: "Vencido",
    dialog: {
      title: "Registrar pedido LGPD",
      kind: "Tipo",
      email: "E-mail de quem pediu",
      notes: "Notas",
      submit: "Registrar",
      saved: "Pedido registrado com prazo de 15 dias.",
      statusChanged: (s: string) => `Pedido marcado como ${s.toLowerCase()}.`,
    },
    access: "Revisão de acessos",
    accessIntro: "Quem entra no Estúdio, com papéis, último acesso e segundo fator.",
    accessTable: "Acessos da equipe",
    accessCol: { name: "Nome", roles: "Papéis", last: "Último acesso", mfa: "2FA" },
    mfaOn: "Ativo",
    mfaOff: "Sem 2FA",
    never: "Nunca entrou",
    keys: "Chaves e rotação",
    keysIntro:
      "Só metadados: o valor de cada chave vive nas variáveis de ambiente (Vercel e Supabase).",
    keysTable: "Chaves",
    keysCol: { key: "Variável", label: "Uso", rotated: "Última rotação", due: "Próxima" },
    rotate: "Marcar como rotacionada",
    rotated: (key: string) => `${key} marcada como rotacionada hoje.`,
    neverRotated: "Nunca registrada",
    dueSoon: "Vence em breve",
    overdueKey: "Vencida",
  },
  governance: {
    title: "Governança editorial",
    intro:
      "Correções, direito de resposta, denúncias, aprovações e a proporção entre publicação humana e automática nos últimos 7 dias.",
    kpis: "Indicadores editoriais",
    correctionsOpen: "Correções abertas",
    correctionsOverdue: "Correções vencidas",
    rightOfReply: "Direito de resposta aberto",
    reportsOpen: "Denúncias abertas",
    approvalsPending: "Aprovações pendentes",
    publishedHuman: "Publicadas por pessoa (7 d)",
    publishedAuto: "Publicadas automaticamente (7 d)",
    correctionsPublished: "Correções publicadas (30 d)",
    autoShare: (pct: number) => `${pct}% das publicações dos últimos 7 dias foram automáticas.`,
    principles: "Princípios e políticas",
    links: [
      { href: "/principios-editoriais", label: "Princípios editoriais" },
      { href: "/correcoes", label: "Política de correções" },
      { href: "/direito-de-resposta", label: "Direito de resposta" },
    ],
    queues: "Filas",
    queueLinks: [
      { href: "/estudio/correcoes", label: "Correções e direito de resposta" },
      { href: "/estudio/denuncias", label: "Denúncias de leitores" },
      { href: "/estudio/control/aprovacoes", label: "Aprovações" },
      { href: "/estudio/control/regras", label: "Regras de autonomia" },
    ],
  },
  integrations: {
    title: "Integrações",
    intro:
      "Serviços ligados ao portal e ao pipeline, com o estado de configuração de cada um. Nenhum valor de chave aparece aqui.",
    table: "Integrações",
    col: { name: "Serviço", role: "Para quê", status: "Situação", detail: "Detalhe" },
    configured: "Configurada",
    missing: "Não configurada",
    degraded: "Degradada",
    items: {
      supabase: { name: "Supabase", role: "Banco, Auth, Storage, filas e cron" },
      openrouter: { name: "OpenRouter", role: "Modelos de IA (Vercel AI SDK)" },
      vercel: { name: "Vercel", role: "Hospedagem, cron e previews" },
      cron: { name: "Cron e workers", role: "Ciclo de 30 minutos e filas" },
      media: { name: "Armazenamento de mídia", role: "Cópias de imagem e uploads" },
      email: { name: "E-mail transacional", role: "Links de login, convites e avisos" },
      push: { name: "Push (PWA)", role: "Notificações web push" },
    },
    detail: {
      fake: "Provedor de teste (AI_PROVIDER=fake)",
      models: (n: number) => `${n} ${plural(n, "modelo registrado", "modelos registrados")}`,
      lastRun: (when: string) => `Último ciclo: ${when}`,
      noRun: "Nenhum ciclo registrado",
      lastCall: (when: string) => `Última chamada: ${when}`,
      noCall: "Nenhuma chamada registrada",
      store: (kind: string) => `Modo: ${kind}`,
      viaAuth: "Enviado pelo Auth do Supabase",
      pwa: "Configurado pelo workstream do PWA",
      env: (name: string) => `Ambiente: ${name}`,
      local: "Ambiente local",
    },
    flags: "Chaves de recurso relacionadas",
  },
  settings: {
    title: "Configurações",
    intro:
      "Parâmetros gerais com grade no banco. Cada mudança fica na auditoria com o valor anterior e o novo.",
    table: "Configurações",
    col: { key: "Chave", value: "Valor", updated: "Atualizado" },
    save: "Salvar",
    saved: (key: string) => `${key} salva.`,
    invalid: "Valor fora da faixa permitida.",
    labels: {
      "sources.default_frequency_minutes": "Frequência padrão de coleta (minutos, múltiplo de 30)",
      "sources.fast_lane_max": "Vagas na via rápida de fontes (0 a 20)",
      "seo.title_template": "Modelo de título (SEO)",
      "security.session_hours": "Duração máxima da sessão (horas)",
      "security.retention_days": "Retenção de eventos individuais (dias, de 30 a 90)",
      "security.require_2fa": "Exigir segundo fator da equipe (ainda não aplicado)",
      "ads.max_per_page": "Patrocinados por página (0 a 3)",
    } as Record<string, string>,
    yes: "Sim",
    no: "Não",
  },
} as const;
