/** Textos da Administração (A01–A06, P5-T8). */
import type { HomeModuleId } from "@/lib/admin/home-layout";
import type { MergeSuggestion } from "@/lib/admin/taxonomy";

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const ADMIN_TEXT = {
  sectionLabel: "Administração",
  errorTitle: "Não foi possível carregar esta tela",
  errorBody: "Tente de novo em instantes. Se continuar, veja os logs do Control Center.",
  retry: "Tentar de novo",
  genericError: "Não foi possível concluir. Tente de novo.",
  save: "Salvar",
  cancel: "Cancelar",
  none: "—",
  dashboard: {
    title: "Administração",
    intro:
      "Pessoas, papéis, equipes, taxonomia, home, publicidade, SEO, auditoria, segurança e configurações do CityNews Cuiabá. Toda ação fica na auditoria.",
    kpis: "Indicadores da administração",
    users: "Pessoas na equipe",
    invites: "Convites pendentes",
    approvals: "Aprovações aguardando",
    teams: "Equipes",
    homeVersion: "Versão da home publicada",
    tagSuggestions: "Tags duplicadas sugeridas",
    areas: "Áreas",
    open: "Abrir",
  },
  users: {
    title: "Usuários",
    intro:
      "Quem tem acesso ao Estúdio, com papel e editorias. Convite chega por e-mail; papel de administração só entra com aprovação de outra pessoa.",
    invite: "Convidar pessoa",
    table: "Pessoas da equipe",
    col: { name: "Nome", email: "E-mail", roles: "Papéis", status: "Situação", actions: "Ações" },
    pending: "Convite pendente",
    active: "Ativa",
    edit: "Editar papéis",
    empty: "Nenhuma pessoa na equipe.",
    inviteDialog: {
      title: "Convidar pessoa para o Estúdio",
      name: "Nome",
      email: "E-mail",
      role: "Papel",
      sections: "Editorias (só para editor)",
      hint: "A pessoa recebe um link para criar a senha. Administração não vai por convite.",
      submit: "Enviar convite",
      sent: (email: string) =>
        `Convite enviado para ${email}. Aparece como “Convite pendente” até o primeiro acesso.`,
      exists: "Já existe uma conta com este e-mail.",
      invalidEmail: "Informe um e-mail válido. Exemplo: ana@exemplo.com",
    },
    rolesDialog: {
      title: (name: string) => `Papéis de ${name}`,
      hint: "Marque os papéis. Editor precisa de pelo menos uma editoria. Administração abre um pedido de aprovação para outra pessoa.",
      submit: "Salvar papéis",
      saved: "Papéis atualizados.",
      adminRequested:
        "Pedido de papel de administração aberto: outra pessoa da administração precisa aprovar na caixa de aprovações.",
      adminPending: "Pedido de administração aguardando aprovação",
      adminApproved: "Aprovado: aplicar papel de administração",
      apply: "Aplicar",
      applied: "Papel de administração aplicado.",
      revokeRequested:
        "Retirar a administração também precisa de outra pessoa da administração: pedido aberto na caixa de aprovações. Depois de aprovado, use “Aplicar revogação”.",
      revokePending: "Revogação de administração aguardando aprovação",
      revokeApproved: "Revogação aprovada: aplicar",
      revokeApply: "Aplicar revogação",
      revokeApplied: "Papel de administração revogado.",
      self: "Ninguém altera os próprios papéis.",
      editorNeedsSection: "Editor precisa de pelo menos uma editoria.",
      justification: "Justificativa (para o pedido de administração)",
      justificationRequired: "Explique o motivo da mudança no papel de administração.",
    },
  },
  roles: {
    title: "Papéis e permissões",
    intro:
      "Matriz de permissões em vigor (docs/architecture.md §6). Mudar a matriz é mudança de código; aqui ela é consultada e conferida com quem tem cada papel.",
    table: "Matriz de permissões por papel",
    action: "Ação",
    grant: {
      all: "Sim",
      section: "Por editoria",
      own: "Próprias",
      first: "1ª assinatura",
      second: "2ª assinatura",
      no: "Não",
    },
    people: "Pessoas por papel",
    nobody: "Ninguém",
    criticalTitle: "Mudanças que exigem duas pessoas",
    critical: [
      "Ativar regras de autonomia e desligar a revisão obrigatória",
      "Publicar prompt em produção",
      "Pesos de recomendação",
      "Papel de administração",
      "Religar a publicação automática (proteção)",
      "Push urgente",
    ],
  },
  teams: {
    title: "Equipes",
    intro:
      "Equipes editoriais com responsável, editorias e integrantes. Servem para atribuição e para o calendário; a permissão continua vindo do papel de cada pessoa.",
    create: "Nova equipe",
    table: "Equipes",
    col: { name: "Equipe", lead: "Responsável", sections: "Editorias", members: "Integrantes" },
    empty: "Nenhuma equipe ainda.",
    dialog: {
      titleNew: "Nova equipe",
      titleEdit: (name: string) => `Editar ${name}`,
      name: "Nome",
      description: "Descrição",
      lead: "Responsável",
      noLead: "Sem responsável",
      sections: "Editorias",
      members: "Integrantes",
      submit: "Salvar equipe",
      remove: "Apagar equipe",
      confirmRemove: (name: string) =>
        `Apagar a equipe ${name}? As pessoas continuam com os papéis.`,
      saved: (name: string) => `Equipe ${name} salva.`,
      removed: (name: string) => `Equipe ${name} apagada.`,
      nameTaken: "Já existe uma equipe com este nome.",
    },
  },
  taxonomy: {
    title: "Taxonomia",
    intro:
      "Editorias, subeditorias, tags e lugares (bairros e municípios). Mesclar tags duplicadas preserva os vínculos das matérias.",
    sections: "Editorias e subeditorias",
    sectionsTable: "Editorias",
    col: {
      section: "Editoria",
      slug: "Endereço",
      parent: "Editoria-mãe",
      category: "Categoria de regras",
    },
    addSection: "Nova subeditoria",
    sectionDialog: {
      title: "Nova subeditoria",
      name: "Nome",
      parent: "Editoria-mãe",
      submit: "Criar",
      created: (name: string) => `Subeditoria ${name} criada.`,
      slugTaken: "Já existe uma editoria com este endereço.",
    },
    renameSection: "Renomear",
    renameDialog: {
      title: (name: string) => `Renomear ${name}`,
      name: "Novo nome",
      submit: "Renomear",
      done: (from: string, to: string) => `${from} agora se chama ${to}.`,
    },
    tags: "Tags",
    tagsTable: "Tags em uso",
    tagCol: { tag: "Tag", articles: "Matérias", items: "Itens coletados" },
    tagsEmpty: "Nenhuma tag em uso.",
    suggestions: "Sugestões de mesclagem",
    suggestionsIntro:
      "Tags que só diferem por acento, caixa, espaço ou plural. Sugestão automática; a mesclagem é sempre uma decisão sua e mantém os vínculos.",
    suggestionsEmpty: "Nenhuma tag duplicada encontrada.",
    reason: {
      accent: "acento",
      case: "maiúsculas",
      plural: "plural",
      spacing: "espaço",
    } satisfies Record<MergeSuggestion["reason"], string>,
    mergeInto: (from: string, into: string) => `Mesclar “${from}” em “${into}”`,
    merge: "Mesclar",
    merged: (from: string, into: string, n: number) =>
      `“${from}” mesclada em “${into}”: ${n} ${plural(n, "vínculo preservado", "vínculos preservados")}.`,
    mergeManual: "Mesclar duas tags",
    mergeFrom: "Tag que some",
    mergeTo: "Tag que fica",
    places: "Lugares",
    placesTable: "Bairros e municípios",
    placeCol: {
      name: "Nome",
      kind: "Tipo",
      slug: "Endereço",
      phrase: "Nas frases",
      status: "Situação",
    },
    kind: { bairro: "Bairro", municipio: "Município" },
    active: "Ativo",
    inactive: "Inativo",
    addPlace: "Novo lugar",
    placeDialog: {
      title: "Novo lugar",
      name: "Nome",
      kind: "Tipo",
      phrase: "Forma nas frases",
      phraseHint: "Exemplo: “no Coxipó”, “em Várzea Grande”.",
      submit: "Criar",
      created: (name: string) => `${name} criado.`,
      slugTaken: "Já existe um lugar com este endereço.",
    },
    togglePlace: (active: boolean) => (active ? "Desativar" : "Ativar"),
    placeToggled: (name: string, active: boolean) =>
      `${name} ${active ? "ativado" : "desativado"}.`,
  },
  home: {
    title: "Home e módulos",
    intro:
      "Ordem e ativação dos módulos abaixo da primeira dobra. Manchete e “Agora” são fixos: 100% CityNews. Reordene com Alt + setas, salve o rascunho e publique.",
    published: (v: number, when: string, who: string) =>
      `Publicada: versão ${v}, ${when}, por ${who}`,
    noPublished: "Nenhuma versão publicada; o portal usa a ordem padrão.",
    draft: (v: number) => `Rascunho: versão ${v}`,
    noDraft: "Sem rascunho: as mudanças criam uma versão nova.",
    list: "Módulos da home",
    help: "Com o foco num módulo, Alt + seta para cima ou para baixo muda a posição. Os botões fazem o mesmo.",
    moveUp: (name: string) => `Subir ${name}`,
    moveDown: (name: string) => `Descer ${name}`,
    enabled: (name: string) => `${name} ativo`,
    position: (i: number, n: number) => `posição ${i} de ${n}`,
    moved: (name: string, i: number) => `${name} agora na posição ${i}.`,
    note: "Nota da versão",
    saveDraft: "Salvar rascunho",
    publish: "Publicar",
    discard: "Descartar rascunho",
    saved: (v: number) => `Rascunho salvo como versão ${v}.`,
    publishedMsg: (v: number) => `Versão ${v} publicada. A home atualiza em até 1 minuto.`,
    discarded: "Rascunho descartado.",
    unchanged: "Nada mudou em relação à versão publicada.",
    noneEnabled: "Deixe pelo menos um módulo ativo.",
    unsaved: "Mudanças ainda não salvas.",
    history: "Histórico de versões",
    historyCol: {
      version: "Versão",
      status: "Situação",
      who: "Quem",
      when: "Quando",
      note: "Nota",
    },
    status: { draft: "Rascunho", published: "Publicada", archived: "Arquivada" },
    preview: "Prévia da ordem",
    previewFixed: "Manchete e Agora (fixos)",
    modules: {
      topics: "Assuntos em destaque",
      collections: "Coleções",
      nearby: "Perto de você",
      agenda_services: "Agenda e serviços",
      sections: "Blocos de editoria",
      most_read: "Mais lidas",
      sources: "Fontes em destaque",
      panorama: "Veja também em outros portais",
      newsletter: "Newsletter",
    } satisfies Record<HomeModuleId, string>,
  },
} as const;
