import type { IntegrationId, IntegrationState } from "@/lib/admin/integrations";
import type { SettingKey } from "@/lib/admin/settings";

/** Textos da Administração (P5-T9): publicidade, SEO, notificações, auditoria, segurança, governança, integrações e configurações. */
export const ADMIN_OPS = {
  common: {
    retry: "Tentar de novo",
    errorTitle: "Não foi possível carregar esta tela",
    errorBody: "O banco não respondeu. Nada foi alterado. Tente de novo em instantes.",
    save: "Salvar",
    any: "Todos",
    yes: "Sim",
    no: "Não",
    none: "Nenhum",
    updatedAt: "Atualizado em",
    ok: {
      campanha: "Campanha salva.",
      ativada: "Campanha ativada.",
      pausada: "Campanha pausada.",
      flag_on: "Patrocínio ligado.",
      flag_off: "Patrocínio desligado.",
      settings: "Configurações salvas.",
      pedido: "Pedido de aprovação enviado. Outra pessoa precisa aprovar em Aprovações.",
      enviado: "Push urgente colocado na fila de envio.",
      liberado: "Bloqueios de login liberados.",
    },
    erro: {
      forbidden: "Seu papel não permite esta ação.",
      invalid: "Confira os campos e tente de novo.",
      unavailable: "Não foi possível salvar agora. Nada foi alterado.",
      approval_required:
        "Envio bloqueado: falta a aprovação de outra pessoa para esta matéria (push urgente).",
      not_found: "Matéria não encontrada ou ainda não publicada.",
    },
  },
  ads: {
    title: "Publicidade e patrocinados",
    intro:
      "Campanhas de patrocinado nativo. As regras abaixo são fixas e valem para qualquer campanha. O patrocínio fica desligado até a migração para um plano comercial (B-003).",
    loading: "Carregando as campanhas",
    flagTitle: "Patrocínio no portal",
    flagOff: "Desligado. Nenhum patrocinado aparece no portal.",
    flagOn: "Ligado. Só campanhas ativas e dentro do período entram.",
    flagOnAction: "Ligar patrocínio",
    flagOffAction: "Desligar patrocínio",
    flagAdminOnly: "Só a pessoa administradora liga ou desliga o patrocínio.",
    rulesTitle: "Regras fixas",
    rules: [
      "No máximo 1 patrocinado a cada 6 cards, e um por lista.",
      "Nunca em Política.",
      "Nunca em matéria urgente, na manchete ou em respostas da busca com IA.",
      "O rótulo PATROCINADO fica sempre visível, em texto, com link para o anunciante.",
      "Conteúdo patrocinado nunca entra como fonte de uma resposta de IA.",
    ],
    formTitle: "Nova campanha",
    advertiser: "Anunciante",
    startsOn: "Início",
    endsOn: "Fim",
    sections: "Editorias permitidas",
    sectionsHint: "Política não aparece na lista: é proibida por regra.",
    headline: "Título da peça",
    url: "Link do anunciante (https)",
    create: "Criar campanha",
    tableCaption: "Campanhas de patrocinado",
    colAdvertiser: "Anunciante",
    colPeriod: "Período",
    colSections: "Editorias",
    colStatus: "Situação",
    colPreview: "Pré-visualização",
    colActions: "Ações",
    active: "Ativa",
    paused: "Pausada",
    expired: "Encerrada",
    scheduled: "Agendada",
    activate: (a: string) => `Ativar campanha de ${a}`,
    pause: (a: string) => `Pausar campanha de ${a}`,
    activateShort: "Ativar",
    pauseShort: "Pausar",
    empty: "Nenhuma campanha ainda",
    emptyBody: "Crie a primeira campanha no formulário acima. Ela começa pausada.",
    previewNote: "Assim aparece no portal, sempre com o rótulo.",
    sponsoredLabel: "PATROCINADO",
  },
  seo: {
    title: "SEO",
    intro:
      "Padrões de título e descrição, e o que o portal já publica de sitemap e robots (somente leitura).",
    loading: "Carregando o SEO",
    defaultsTitle: "Padrões",
    titleTemplate: "Modelo do título",
    titleTemplateHint:
      "Use {titulo} onde entra o título da página. Exemplo: {titulo} · CityNews Cuiabá",
    defaultDescription: "Descrição padrão",
    defaultDescriptionHint:
      "Usada quando a página não tem descrição própria. De 20 a 300 caracteres.",
    sample: "Exemplo com o modelo atual:",
    sampleTitle: "Ponte sobre o Rio Cuiabá reabre",
    sitemapsTitle: "Sitemaps publicados",
    sitemapsCaption: "Sitemaps do portal",
    colPath: "Endereço",
    colWhat: "Conteúdo",
    sitemaps: [
      { path: "/sitemap.xml", what: "Índice que aponta para os demais" },
      { path: "/sitemap-articles.xml", what: "Matérias publicadas" },
      { path: "/sitemap-news.xml", what: "Notícias das últimas 48 horas" },
      { path: "/sitemap-topics.xml", what: "Assuntos" },
      { path: "/sitemap-pages.xml", what: "Páginas fixas e editorias" },
    ],
    robotsTitle: "robots.txt",
    robotsCaption: "Regras do robots.txt",
    colRule: "Regra",
    colPaths: "Caminhos",
    robotsAllow: "Permitido",
    robotsDisallow: "Bloqueado",
    robotsSitemap: "Sitemap indicado",
    missingTitle: "Páginas sem descrição",
    missingBody: (m: number, t: number) =>
      m === 0
        ? `Todas as ${t} matérias publicadas têm linha fina (descrição).`
        : `${m} de ${t} matérias publicadas estão sem linha fina, que serve de descrição.`,
    readonlyNote: "Sitemap e robots são gerados pelo código do portal e não se editam aqui.",
  },
  notify: {
    title: "Notificações",
    intro:
      "Push de urgente só sai com aprovação de outra pessoa. Sem provedor de e-mail, o e-mail do plantão fica na fila (B-005).",
    loading: "Carregando as notificações",
    urgentTitle: "Push urgente",
    urgentBody:
      "1. Peça a aprovação com uma justificativa. 2. Outra pessoa aprova em Aprovações. 3. Volte aqui e envie. Cada aprovação vale para um envio, por até 24 horas.",
    article: "Matéria",
    justification: "Justificativa",
    justificationHint: "Por que este aviso não pode esperar?",
    request: "Pedir aprovação",
    send: (t: string) => `Enviar push: ${t}`,
    sendShort: "Enviar push",
    approvalsCaption: "Pedidos de push urgente nas últimas 24 horas",
    colArticle: "Matéria",
    colStatus: "Situação",
    colRequested: "Pedido em",
    colActions: "Ação",
    st: {
      pending: "Aguarda outra pessoa",
      approved: "Aprovado",
      rejected: "Recusado",
      used: "Já enviado",
    },
    approvalsEmpty: "Nenhum pedido nas últimas 24 horas",
    approvalsEmptyBody: "Escolha uma matéria acima para pedir a aprovação.",
    historyTitle: "Histórico de envios",
    historyCaption: "Envios de push urgente",
    colWhen: "Quando",
    colBy: "Enviado por",
    dispatch: { queued: "Na fila de envio", sent: "Enviado", failed: "Falhou" },
    historyEmpty: "Nenhum envio ainda",
    historyEmptyBody: "Os envios aprovados aparecem aqui.",
    emailTitle: "E-mail do plantão",
    emailBody: (n: number) =>
      n === 0
        ? "Nenhum e-mail na fila. O envio real começa quando houver provedor de e-mail (B-005)."
        : `${n} e-mail(s) na fila, sem envio até haver provedor de e-mail (B-005).`,
    limitsTitle: "Limites e janela de silêncio",
    noCandidates: "Nenhuma matéria publicada para escolher.",
  },
  audit: {
    title: "Auditoria",
    intro:
      "Registro de tudo que a equipe fez, somente leitura. Endereços de IP aparecem inteiros só para administradores.",
    loading: "Carregando a auditoria",
    filters: "Filtros da auditoria",
    actor: "Pessoa (id)",
    action: "Ação",
    object: "Objeto",
    from: "De",
    to: "Até",
    apply: "Filtrar",
    clear: "Limpar filtros",
    export: "Exportar CSV",
    exportNote: "Exporta até 5.000 registros do filtro atual.",
    maskedNote: "Endereços de IP aparecem mascarados para o seu papel.",
    caption: "Registros de auditoria",
    colWhen: "Quando",
    colActor: "Pessoa",
    colAction: "Ação",
    colObject: "Objeto",
    colIp: "IP",
    colDetails: "Detalhes",
    empty: "Nenhum registro para estes filtros",
    emptyBody: "Amplie o período ou limpe os filtros.",
    prev: "Página anterior",
    next: "Próxima página",
    page: (n: number) => `Página ${n}`,
    pagination: "Paginação da auditoria",
  },
  security: {
    title: "Segurança e privacidade",
    intro:
      "Sessões da equipe, tentativas de login e limites de uso. Leitura, com uma ação auditada.",
    loading: "Carregando a segurança",
    sessionsTitle: "Sessões da equipe",
    sessionsCaption: "Sessões ativas por pessoa da equipe",
    colPerson: "Pessoa",
    colRoles: "Papéis",
    colSessions: "Sessões",
    colLast: "Última atividade",
    colIp: "Último IP",
    colAgent: "Navegador",
    sessionsEmpty: "Nenhuma pessoa da equipe",
    sessionsEmptyBody: "Cadastre pessoas em Usuários.",
    never: "Nunca",
    maskedNote: "Endereços de IP aparecem mascarados para o seu papel.",
    limitsTitle: "Limites de uso nas últimas 24 horas",
    limitsCaption: "Uso dos limites por tipo",
    colBucket: "Tipo",
    colKeys: "Conexões distintas",
    colHits: "Tentativas",
    colMax: "Maior número em uma hora",
    limitsEmpty: "Nenhum uso registrado",
    limitsEmptyBody: "Os contadores aparecem quando há tentativas.",
    buckets: {
      login_fail: "Falhas de login",
      auth_email: "Links de acesso por e-mail",
      alert: "Cadastro de alertas",
      newsletter: "Newsletter",
      report: "Denúncias",
      event_submission: "Sugestões de evento",
      right_of_reply: "Direito de resposta",
      playground: "Testes de agente",
      studio_audit_denied: "Ações negadas no Estúdio",
    } as Record<string, string>,
    policyTitle: "Política de acesso",
    policy: [
      "Rotas do Estúdio exigem sessão e papel; sem permissão, a tentativa é negada e auditada.",
      "Login nunca é obrigatório para leitores. Falhas seguidas bloqueiam por um tempo (limite por e-mail e conexão).",
      "Segredos ficam só em variáveis de ambiente e nunca aparecem em tela, log ou exportação.",
      "2FA da equipe, retenção e a fila de pedidos LGPD entram numa etapa própria.",
    ],
    clearTitle: "Liberar bloqueios de login",
    clearBody:
      "Remove os contadores de falhas de login. Use só quando alguém da equipe ficou bloqueado. A ação é auditada.",
    clear: "Liberar bloqueios",
    clearAdminOnly: "Só a pessoa administradora libera bloqueios.",
  },
  governance: {
    title: "Governança editorial",
    intro:
      "As regras que valem para toda publicação, em leitura. Mudanças passam por aprovação de duas pessoas.",
    loading: "Carregando a governança",
    rulesTitle: "Publicação automática",
    rulesCaption: "Estado das regras de publicação",
    colItem: "Item",
    colState: "Estado",
    rulesVersion: "Versão das regras em vigor",
    rulesNone: "Nenhuma versão ativa",
    forceReview: "Toda matéria vai para revisão humana",
    pending: "Aprovações pendentes",
    flags: {
      image_reproduction_enabled: "Reprodução de imagem de terceiros",
      personalization_enabled: "Personalização com consentimento",
      sponsored_enabled: "Patrocinado nativo",
    } as Record<string, string>,
    flagOn: "Ligada",
    flagOff: "Desligada",
    flagMissing: "Chave não cadastrada",
    principlesTitle: "Princípios que não mudam",
    principles: [
      {
        title: "Origem sempre visível",
        body: "Todo conteúdo mostra seus rótulos de origem, em texto.",
      },
      {
        title: "Agregado não é republicado",
        body: "Só título, data, resumo de até 2 frases e link para o original.",
      },
      { title: "Segurança e urgência", body: "Nunca publicam sozinhas: passam por uma pessoa." },
      {
        title: "IA só com fonte",
        body: "Com menos de 2 fontes relevantes, a busca com IA recusa e explica.",
      },
      { title: "Personalização", body: "Só com consentimento; nunca infere atributo protegido." },
      {
        title: "Imagem gerada",
        body: "Nunca fotorrealista de pessoa real, nem para crime, tragédia ou saúde individual.",
      },
    ],
    links: { rules: "Ver regras de autonomia", approvals: "Ver aprovações" },
  },
  integrations: {
    title: "Integrações",
    intro:
      "Estado de cada serviço ligado ao CityNews. Nenhum segredo ou variável de ambiente aparece aqui.",
    loading: "Carregando as integrações",
    caption: "Estado das integrações",
    colName: "Serviço",
    colState: "Estado",
    colWhat: "O que faz",
    colNote: "Situação e próximo passo",
    names: {
      supabase: "Supabase",
      openrouter: "OpenRouter",
      email: "E-mail",
      google: "Google (login)",
      vercel: "Vercel",
    } as Record<IntegrationId, string>,
    what: {
      supabase: "Banco de dados, contas, filas e armazenamento.",
      openrouter: "Modelos de IA para resumo, verificação e busca.",
      email: "Newsletter, alertas por e-mail e e-mail do plantão.",
      google: "Botão de entrar com Google.",
      vercel: "Hospedagem e publicações de prévia.",
    } as Record<IntegrationId, string>,
    states: {
      connected: "Conectado",
      simulated: "Simulado",
      pending: "Pendente",
      error: "Com erro",
      off: "Não se aplica",
    } as Record<IntegrationState, string>,
    notes: {
      supabase: {
        connected: "Responde normalmente.",
        error: "Configurado, mas não respondeu. Veja os logs e o painel do Supabase.",
        off: "Variáveis do Supabase ausentes neste ambiente.",
      },
      openrouter: {
        connected: "Chave configurada. Modelos registrados no banco.",
        simulated:
          "Usando o provedor de teste (sem chave). Cadastre a chave na Vercel para ligar (B-008).",
      },
      email: {
        pending: (n: string) =>
          `Envio na fila (${n} na fila do plantão), sem provedor. O e-mail de acesso segue pelo SMTP do Supabase (B-005).`,
      },
      google: {
        connected: "Botão Google liberado.",
        pending:
          "Aguardando credenciais no Google Cloud e no Supabase (B-006). O botão fica desligado.",
      },
      vercel: {
        connected: (env: string) => (env ? `Ambiente ${env}.` : "Em produção na Vercel."),
        off: "Execução fora da Vercel (local ou teste).",
      },
    },
  },
  settings: {
    title: "Configurações",
    intro:
      "Ajustes gerais do portal. Não há segredos aqui: chaves ficam nas variáveis de ambiente.",
    loading: "Carregando as configurações",
    contactTitle: "Contatos da redação",
    contactEmail: "E-mail da redação",
    tipEmail: "E-mail de pautas",
    notifyTitle: "Limites de notificação",
    quietStart: "Início do silêncio",
    quietEnd: "Fim do silêncio",
    quietHint:
      "Horário de Cuiabá, no formato HH:MM. Sem push nesta janela, exceto urgente aprovado.",
    maxPush: "Push por leitor por dia",
    maxPushHint: "De 1 a 10.",
    readonlyTitle: "Fixos do portal",
    readonlyCaption: "Valores fixos do portal",
    colName: "Ajuste",
    colValue: "Valor",
    fixed: [
      { name: "Idioma da interface", value: "Português do Brasil" },
      { name: "Fuso horário", value: "America/Cuiaba" },
      { name: "Ciclo de publicação", value: "A cada 30 minutos" },
    ],
    savedAt: "Última alteração",
  },
  fieldLabels: {
    "seo.title_template": "Modelo do título",
    "seo.default_description": "Descrição padrão",
    "general.contact_email": "E-mail da redação",
    "general.tip_email": "E-mail de pautas",
    "notify.quiet_start": "Início do silêncio",
    "notify.quiet_end": "Fim do silêncio",
    "notify.max_push_per_day": "Push por leitor por dia",
  } as Record<SettingKey, string>,
  fieldError: (key: SettingKey, label: string) => `Confira o campo "${label}" (${key}).`,
} as const;
