/** Textos do painel de banners no Estúdio (ADS-T4, A07 · Publicidade). */

export const SLOT_NAME: Record<string, string> = {
  TOP: "Faixa de topo",
  "RAIL-A": "Retângulo lateral",
  "RAIL-B": "Arranha-céu lateral",
  MID: "Faixa entre blocos",
  "ART-1": "No texto",
  "ART-2": "Fim da matéria",
  STICKY: "Rodapé fixo (celular)",
};

export const PLACEMENT_STATUS_LABEL = {
  draft: "Rascunho",
  active: "No ar",
  paused: "Pausado",
  ended: "Encerrado",
} as const;

export const ADS_ADMIN_TEXT = {
  tabs: {
    label: "Seções da publicidade",
    occupancy: "Campos",
    banners: "Banners",
    report: "Relatório",
    sponsored: "Patrocinados",
  },
  occupancy: {
    title: "Ocupação dos campos",
    intro:
      "Cada campo mostra uma peça paga quando houver; sem peça paga, entram as peças da casa. Nunca há banner em Política, Justiça, Segurança ou Saúde.",
    paid: "Com anunciante",
    house: "Só peças da casa",
    empty: "Vazio",
    counts: (paid: number, house: number) =>
      `${paid} ${paid === 1 ? "peça paga" : "peças pagas"} · ${house} da casa`,
    endingSoon: (n: number) =>
      `${n} ${n === 1 ? "veiculação termina" : "veiculações terminam"} em até 3 dias`,
    off: "Os banners estão desligados em Interruptores: nenhum campo aparece no portal.",
  },
  banners: {
    title: "Banners",
    newTitle: "Novo banner",
    empty: "Nenhum banner cadastrado.",
    house: "CityNews (casa)",
    period: (from: string, to: string) => `${from} a ${to}`,
    sectionsAll: "Todas as editorias permitidas",
    weight: (n: number) => `peso ${n}`,
    pause: "Pausar",
    resume: "Pôr no ar",
    end: "Encerrar",
    open: "Abrir o link do anunciante",
  },
  form: {
    slot: "Campo",
    format: "Formato",
    formatHint: "A imagem precisa ter exatamente este tamanho ou o dobro (tela de alta densidade).",
    image: "Imagem (PNG, JPEG ou WebP, até 200 KB)",
    name: "Nome interno",
    advertiser: "Anunciante",
    advertiserHint: "Em branco = peça da casa.",
    href: "Link (https://)",
    alt: "Texto alternativo",
    altHint: "O que a peça diz, para quem usa leitor de tela.",
    startsOn: "Início",
    endsOn: "Fim",
    sections: "Editorias",
    sectionsHint: "Nenhuma marcada = todas as permitidas.",
    weight: "Peso na rotação (1 a 100)",
    maxPerDay: "Teto de impressões por dia",
    maxPerDayHint: "Em branco = sem teto.",
    status: "Situação",
    submit: "Cadastrar banner",
    sending: "Enviando…",
  },
  report: {
    title: "Relatório",
    from: "De",
    to: "Até",
    apply: "Ver período",
    csv: "Baixar CSV",
    empty: "Nenhuma contagem no período.",
    impressions: "Impressões",
    views: "Visualizações",
    clicks: "Cliques",
    ctr: "CTR",
    viewRate: "Taxa de visualização",
    bySlot: "Por campo",
    byDay: "Por dia",
    byAdvertiser: "Por anunciante",
    bySection: "Por editoria",
    key: "Item",
    note: "Contagem agregada, sem identificar quem viu: impressão quando a peça aparece, visualização com metade dela na tela por 1 segundo, clique pela rota de redirecionamento. Robôs não contam.",
  },
  error: {
    slot: "Escolha um campo de banner.",
    format: "Este campo não tem esse formato.",
    type: "Envie PNG, JPEG ou WebP.",
    size: "A imagem passa de 200 KB.",
    dimensions: (w: number, h: number) =>
      `A imagem precisa ter ${w}×${h} px (ou ${w * 2}×${h * 2} px).`,
    period: "O fim precisa ser igual ou depois do início.",
    forbiddenSection: "Política, Justiça, Segurança e Saúde (com subeditorias) não recebem banner.",
    storage: "Não foi possível guardar a imagem agora. Tente de novo.",
    invalid: "Confira os campos do banner.",
    https: "O link precisa começar com https://",
    period365: "Período inválido.",
  },
  saved: (name: string) => `Banner "${name}" cadastrado.`,
  statusSaved: (label: string) => `Situação alterada: ${label}.`,
};
