/** Textos das telas O10 agentes, O11 modelos, O12 prompts e O15 playground (P5-T5). */
import type { PromptStatus } from "@/lib/ai/prompts";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
export const formatBrl = (n: number) => brl.format(n);
const brl6 = new Intl.NumberFormat("pt-BR", {
  style: "currency",
  currency: "BRL",
  minimumFractionDigits: 2,
  maximumFractionDigits: 6,
});
export const formatBrlPrecise = (n: number) => brl6.format(n);

export const PROMPT_STATUS_TEXT: Record<PromptStatus, string> = {
  draft: "Rascunho",
  pending: "Aguardando aprovação",
  production: "Em produção",
  archived: "Arquivada",
  reverted: "Revertida",
};

export const AI_ERROR_TEXT: Record<string, string> = {
  timeout: "Tempo esgotado no provedor.",
  provider: "O provedor falhou.",
  schema: "A resposta não passou no schema do agente.",
  budget_exceeded: "Orçamento diário do agente ou global atingido.",
  disabled: "Agente ou IA desligados, ou sem prompt em produção.",
  injection: "Instrução embutida detectada nos dados: o modelo não foi chamado.",
};

export const AGENTS_TEXT = {
  sectionLabel: "Control Center · IA",
  title: "Agentes",
  intro:
    "Cada agente tem uma função, um modelo com fallback, um prompt em produção e um orçamento diário. Os orçamentos somam o teto global.",
  caption: "Agentes de IA: função, modelo, prompt, orçamento e situação",
  col: {
    agent: "Agente",
    fn: "Função",
    model: "Modelo",
    fallback: "Fallback",
    prompt: "Prompt",
    budget: "Orçamento/dia",
    enabled: "Ligado",
    actions: "Ações",
  },
  budgetSum: (sum: string, total: string) => `Orçamentos somam ${sum} de ${total} por dia.`,
  budgetOver: "Os orçamentos passam do teto global: reduza algum agente antes de salvar.",
  noPrompt: "sem prompt",
  noFallback: "sem fallback",
  prompts: "Prompts e versões",
  playground: "Testar no playground",
  edit: (name: string) => `Editar ${name}`,
  save: "Salvar",
  saving: "Salvando…",
  cancel: "Cancelar",
  enabledLabel: (name: string) => `${name} ligado`,
  budgetLabel: (name: string) => `Orçamento diário de ${name} (R$)`,
  modelLabel: (name: string) => `Modelo de ${name}`,
  fallbackLabel: (name: string) => `Fallback de ${name}`,
  none: "Nenhum",
  saved: "Agente atualizado.",
  readOnly: "Seu papel vê os agentes, mas não edita.",
  empty: "Nenhum agente cadastrado.",
  errorTitle: "Não foi possível carregar",
  errorBody: "O banco não respondeu. Tente de novo em instantes.",
  retry: "Tentar de novo",
  invalidBudget: "Orçamento inválido: use um valor entre 0 e o teto global.",
  sameModel: "Fallback não pode ser o mesmo modelo principal.",
  inactiveModel: "Modelo inativo não pode ser o principal de um agente ligado.",
} as const;

export const MODELS_TEXT = {
  sectionLabel: "Control Center · IA",
  title: "Modelos",
  intro:
    "Modelos registrados no OpenRouter, com preço em reais por 1 000 tokens. Desativar um modelo tira ele das chamadas; agentes que o usam caem no fallback.",
  caption: "Modelos de IA: provedor, limites, preço e situação",
  col: {
    model: "Modelo",
    provider: "Provedor",
    maxTokens: "Máx. tokens",
    temperature: "Temperatura",
    costIn: "R$/1k entrada",
    costOut: "R$/1k saída",
    usedBy: "Usado por",
    status: "Situação",
    actions: "Ações",
  },
  active: "Ativo",
  inactive: "Inativo",
  deactivate: (name: string) => `Desativar ${name}`,
  activate: (name: string) => `Ativar ${name}`,
  notUsed: "nenhum agente",
  updated: "Modelo atualizado.",
  inUse: "Modelo é o principal de um agente ligado: troque o modelo do agente antes de desativar.",
  readOnly: "Seu papel vê os modelos, mas não edita.",
  empty: "Nenhum modelo cadastrado.",
  errorTitle: "Não foi possível carregar",
  errorBody: "O banco não respondeu. Tente de novo em instantes.",
  retry: "Tentar de novo",
  notApplicable: "—",
} as const;

export const PROMPTS_TEXT = {
  sectionLabel: "Control Center · IA",
  title: (agent: string) => `Prompts de ${agent}`,
  intro:
    "Toda versão fica registrada. Admin ou editor-chefe publica em produção numa ação só; o pedido e a aprovação ficam no histórico com quem fez cada passo. Rollback volta para uma versão que já esteve em produção.",
  agentsLink: "Todos os agentes",
  unknownAgent: "Agente não encontrado",
  unknownAgentBody: "Escolha um agente na lista para ver as versões do prompt.",
  productionTitle: (v: number) => `Em produção: v${v}`,
  noProduction: "Nenhuma versão em produção: o agente não é chamado.",
  versionsTitle: "Versões",
  versionsCaption: "Versões do prompt, da mais recente para a mais antiga",
  col: {
    version: "Versão",
    status: "Situação",
    author: "Autor",
    approvals: "Assinaturas",
    rationale: "Motivo",
    when: "Criada em",
    actions: "Ações",
  },
  system: "sistema (migration)",
  someone: "alguém da equipe",
  view: (v: number) => `Ver v${v}`,
  compare: (v: number) => `Comparar v${v} com a produção`,
  compareTitle: (from: number, to: number) => `Diferença entre v${from} e v${to}`,
  compareFrom: (v: number) => `v${v} (produção)`,
  compareTo: (v: number) => `v${v}`,
  bodyLabel: "Texto do prompt",
  noChanges: "Sem diferença de texto.",
  requestPublish: (v: number) => `Pedir publicação da v${v}`,
  publishDirect: (v: number) => `Publicar a v${v}`,
  requested: "Pedido de publicação registrado. Seu papel não publica: fica na caixa de aprovações.",
  requestedPublished: (v: number) => `v${v} em produção. Fica registrado no histórico.`,
  requestJustification: "Justificativa para publicar",
  justificationRequired: "Explique por que esta versão deve ir para produção.",
  approveAndPublish: (v: number) => `Aprovar e publicar v${v}`,
  publish: (v: number) => `Publicar v${v}`,
  published: (v: number) => `v${v} em produção.`,
  publishForbidden: "Só quem aprovou publica.",
  rollback: (v: number) => `Voltar para a v${v}`,
  rolledBack: (to: number, v: number) => `Rollback feito: v${v} em produção com o texto da v${to}.`,
  rollbackConfirm: (v: number) =>
    `Voltar para a v${v} cria uma versão nova com o mesmo texto e marca a atual como revertida. Continuar?`,
  waitApprover: "Aguarda admin ou editor-chefe.",
  pendingBanner: (v: number) => `v${v} aguarda aprovação de admin ou editor-chefe.`,
  approvedBanner: (v: number) => `v${v} aprovada: publique para entrar em produção.`,
  newTitle: "Nova versão",
  newIntro:
    "Comece do texto em produção. O texto vai ao modelo depois da instrução fixa de segurança.",
  newBody: "Texto da nova versão",
  newRationale: "Motivo da mudança",
  rationaleRequired: "Descreva o motivo da mudança.",
  bodyRequired: "O prompt não pode ficar vazio.",
  bodyUnchanged: "O texto é igual ao da produção.",
  create: "Salvar rascunho",
  creating: "Salvando…",
  created: (v: number) => `Rascunho v${v} salvo.`,
  onlyOperator: "Só quem tem o papel de operador de IA escreve versões novas.",
  evalLink: "Rodar regressão desta versão",
  playgroundLink: "Testar no playground",
  errorTitle: "Não foi possível carregar",
  errorBody: "O banco não respondeu. Tente de novo em instantes.",
  retry: "Tentar de novo",
  genericError: "Não foi possível concluir. Tente de novo.",
  forbidden: "Seu papel não permite esta ação.",
  conflict: "Outra pessoa mudou esta versão. Recarregue a tela.",
} as const;

export const PLAYGROUND_TEXT = {
  sectionLabel: "Control Center · IA",
  title: "Playground de testes",
  intro:
    "Rode um agente com uma entrada colada e veja o que o modelo recebeu e devolveu. Nada é publicado: só a chamada fica registrada em custos.",
  fake: "Provedor falso (teste): respostas determinísticas, sem rede e sem segredo.",
  real: "Provedor real (OpenRouter): a chamada custa e conta no orçamento do agente.",
  agent: "Agente",
  promptVersion: "Versão do prompt",
  production: (v: number) => `v${v} · em produção`,
  version: (v: number, status: string) => `v${v} · ${status}`,
  model: "Modelo",
  modelDefault: "Modelo do agente",
  task: "Tarefa (instrução da etapa)",
  taskHint: "O que o agente deve fazer com os dados, como a etapa do pipeline pede.",
  data: "Dados de teste (item colado)",
  dataHint: "Texto externo: vai sanitizado, entre delimitadores de dados, nunca como instrução.",
  caseLabel: "Ou escolha um caso da regressão",
  caseNone: "Nenhum (usar o texto colado)",
  run: "Rodar",
  running: "Rodando…",
  dataRequired: "Cole um item de teste ou escolha um caso.",
  taskRequired: "Descreva a tarefa.",
  resultTitle: "Resultado",
  sanitized: "Entrada sanitizada (o que o modelo viu)",
  injection: "Instrução embutida detectada",
  output: "Saída estruturada",
  valid: "Passou no schema",
  invalid: "Não passou no schema",
  cost: "Custo",
  latency: "Latência",
  noOutput: "Sem saída.",
  saveCase: "Salvar como caso de regressão",
  readOnly: "Seu papel vê o playground, mas não roda.",
  errorTitle: "Não foi possível carregar",
  errorBody: "O banco não respondeu. Tente de novo em instantes.",
  retry: "Tentar de novo",
  genericError: "Não foi possível rodar. Tente de novo.",
  forbidden: "Seu papel não permite esta ação.",
  defaultTask: {
    classify: "Classifique o item em uma editoria, com relevância local e marca de tema sensível.",
    locate: "Identifique o município e o bairro do fato.",
    verify: "Escreva o fato principal e o papel de cada item.",
    write: "Escreva o rascunho normalizado com citações.",
    answer: "Responda à pergunta usando só as fontes numeradas.",
    image: "Decida se o tema permite ilustração gerada.",
    aggregate_summary: "Escreva o resumo de até 2 frases com palavras próprias.",
    source_profiler: "Sugira editorias, localidade e alertas de qualidade da fonte.",
    reviewer: "Decida publish, hold ou archive para a matéria em revisão e justifique.",
  } as Record<string, string>,
} as const;
