/** Alertas (P18): sem conta no navegador; por e-mail só com e-mail confirmado. */
export const ALERTS_TEXT = {
  metaTitle: "Alertas · CityNews Cuiabá",
  metaDescription:
    "Receba avisos do seu bairro, de temas, assuntos, urgentes e da agenda de Cuiabá, no navegador ou por e-mail, sem criar conta.",
  title: "Alertas",
  intro:
    "Avisos do que importa para você em Cuiabá. No navegador, funciona sem conta e fica guardado neste aparelho. Por e-mail, basta confirmar o endereço.",
  limits: "No máximo 3 avisos por dia. Silêncio das 22h às 7h: o que chegar nesse horário espera.",
  whileOpen:
    "Os avisos do navegador chegam enquanto houver uma página do CityNews aberta neste aparelho.",
  activeTitle: "Alertas ativos",
  activeEmpty: "Nenhum alerta ainda",
  activeEmptyText: "Use Criar alerta para receber, por exemplo, os avisos do seu bairro.",
  remove: "Remover",
  removeLabel: (label: string) => `Remover alerta ${label}`,
  createTitle: "Criar alerta",
  kind: "Tipo",
  target: "Alvo",
  frequency: "Frequência",
  channel: "Canal",
  email: "E-mail",
  emailHint: "Enviamos um link para confirmar. Sem confirmação, nada é enviado.",
  emailPlaceholder: "voce@exemplo.com",
  create: "Criar alerta",
  creating: "Criando…",
  kinds: {
    bairro: "Bairro",
    tema: "Tema",
    assunto: "Assunto",
    urgentes: "Urgentes",
    agenda: "Agenda",
  },
  allUrgent: "Todas as notícias urgentes",
  allAgenda: "Novos eventos na agenda",
  frequencies: { immediate: "Imediato", daily: "Resumo diário", weekly: "Resumo semanal" },
  channels: { browser: "Navegador", email: "E-mail" },
  statusActive: "Ativo",
  statusPending: (email: string) => `E-mail não confirmado: enviamos um link para ${email}`,
  created: "Alerta criado. Você recebe o próximo aviso neste navegador.",
  createdEmail:
    "Alerta criado. Enviamos um link de confirmação para o seu e-mail; o alerta começa depois da confirmação. O envio começa em breve.",
  removed: (label: string) => `Alerta ${label} removido.`,
  undo: "Desfazer",
  denied:
    "Seu navegador bloqueou as notificações do CityNews. Para receber alertas aqui, libere as notificações nas configurações do site (ícone de cadeado ao lado do endereço) e tente de novo. Você também pode escolher o canal E-mail.",
  unsupported:
    "Este navegador não mostra notificações. Escolha o canal E-mail para receber os alertas.",
  invalidEmail: "Confira o e-mail digitado. Exemplo: ana@exemplo.com",
  topicsError:
    "Não conseguimos carregar os assuntos agora. Escolha outro tipo de alerta ou tente de novo mais tarde.",
  topicsEmpty: "Ainda não há assuntos para acompanhar. Escolha outro tipo de alerta.",
  rateLimited: "Muitas tentativas a partir desta conexão. Tente de novo em uma hora.",
  error: "Não conseguimos criar o alerta agora. Tente de novo em alguns minutos.",
  notifyTitle: (label: string) => `CityNews · ${label}`,
  digestTitle: (n: number, label: string) =>
    n === 1 ? `1 novidade: ${label}` : `${n} novidades: ${label}`,
  testTitle: "Alertas do CityNews ativados",
  testBody: "É assim que os avisos aparecem neste navegador.",
  confirmAskTitle: "Confirme seu alerta",
  confirmAskText: (email: string) =>
    `Toque no botão para começar a receber este alerta em ${email}. Se não foi você que pediu, feche esta página: nada será enviado.`,
  confirmButton: "Confirmar alerta",
  confirmTitle: "Alerta por e-mail confirmado",
  confirmText: "Pronto: você recebe os avisos neste e-mail quando o envio começar.",
  confirmExpired: "Este link expirou",
  confirmExpiredText: "Por segurança, os links valem por 7 dias. Crie o alerta de novo.",
  confirmInvalid: "Este link não é válido",
  confirmInvalidText: "Confira se o endereço foi copiado inteiro, ou crie o alerta de novo.",
  confirmError: "Não conseguimos confirmar agora",
  confirmErrorText: "Tente de novo em alguns minutos.",
  backToAlerts: "Ir para Alertas",
  mailSubject: "Confirme seu alerta do CityNews",
  mailBody: (label: string, link: string) =>
    `Recebemos um pedido de alerta "${label}" para este e-mail.\n\nPara confirmar, abra: ${link}\n\nSe não foi você, ignore esta mensagem.`,
  loading: "Carregando seus alertas",
} as const;
