/** Pergunte ao CityNews (Perguntar ao CityNews, docs/screens.md P13; spec §5.5). */
export const ASK = {
  title: "Pergunte ao CityNews",
  metaDescription:
    "Faça uma pergunta sobre Cuiabá e receba uma resposta curta com as fontes de cada frase.",
  documentTitle: (q: string) =>
    q ? `Pergunte: ${q} · CityNews Cuiabá` : "Pergunte ao CityNews · CityNews Cuiabá",
  intro:
    "Respostas curtas, só com fontes: cada frase mostra de onde veio. Sem fonte sobre o assunto, o CityNews diz que não encontrou e mostra onde procurar. Não precisa de conta.",
  label: "Sua pergunta",
  placeholder: "Ex.: O que muda no plano de ônibus do CPA?",
  submit: "Perguntar",
  examplesTitle: "Experimente",
  examples: [
    "O que aconteceu em Cuiabá hoje?",
    "O que se sabe sobre o viaduto da Miguel Sutil?",
    "Como está a qualidade do ar em Cuiabá?",
    "O que muda no plano de ônibus do CPA?",
  ],
  conversation: "Conversa",
  youAsked: "Você perguntou",
  processingTitle: "Preparando a resposta",
  processingSteps: [
    "Procurando fontes no CityNews e em outros veículos",
    "Conferindo o que as fontes sustentam",
    "Escrevendo a resposta com a fonte de cada frase",
  ],
  aiGenerated: "Resposta do CityNews",
  asOf: (hour: string) => `Consultado às ${hour}`,
  singleSource: (name: string) =>
    `Baseada em uma única fonte (${name}), ainda sem confirmação de outro veículo.`,
  staleSince: (day: string) => `Informação de ${day}: pode ter mudado desde então.`,
  factsTitle: "O que se sabe",
  inferencesTitle: "Inferência",
  inferencesHint: "Conclusão a partir das fontes, não confirmada por elas.",
  gapsTitle: "Ainda não se sabe",
  conflictsTitle: "Onde as fontes divergem",
  disclaimer: "Pode conter erros. Confira nas fontes.",
  sourcesTitle: "Fontes consultadas",
  foundTitle: "O que encontramos",
  citedBy: (n: number) => `Fonte ${n}`,
  openSource: (name: string) => `Abrir em ${name}`,
  openArticle: "Ler no CityNews",
  newTab: "abre em nova aba",
  feedbackTitle: "Esta resposta ajudou?",
  yes: "Sim",
  no: "Não",
  thanks: "Obrigado pelo retorno.",
  report: "Reportar erro",
  refineTitle: "Continue por aqui",
  traditional: "Ver na busca tradicional",
  insufficientTitle: "Não encontramos fontes para responder",
  insufficientText: (n: number) =>
    n === 0
      ? "O Perguntar ao CityNews só responde com fontes, e não achamos nenhuma sobre isso."
      : `O Perguntar ao CityNews só responde com fontes. Encontramos ${n === 1 ? "1 fonte relacionada" : `${n} fontes relacionadas`}, mas nenhuma responde à pergunta.`,
  suggestion: {
    traditional_search: "Ver na busca tradicional",
    widen_period: "Buscar em qualquer data",
    suggest_story: "Sugerir pauta à redação",
  },
  errorTitle: {
    timeout: "A resposta demorou demais",
    provider: "O serviço de respostas falhou agora",
    rate_limited: (limit: number) => `Você atingiu o limite de ${limit} perguntas por hora`,
    unavailable: "Assistente indisponível",
    off: "Assistente indisponível",
  },
  errorText: {
    timeout: "Tente de novo em instantes. Enquanto isso, a busca tradicional mostra o que há.",
    provider: "Tente de novo em instantes. Enquanto isso, a busca tradicional mostra o que há.",
    rate_limited: (hour: string) =>
      `O limite libera às ${hour}. A busca tradicional continua sem limite.`,
    unavailable: "Pode ser uma instabilidade passageira. A busca tradicional continua funcionando.",
    off: "A redação pausou o assistente. A busca tradicional continua funcionando.",
  },
  retry: "Tentar de novo",
  fallbackTitle: "Resultados da busca tradicional",
  fallbackAll: "Ver todos os resultados",
  fallbackEmpty: "A busca tradicional também não encontrou nada com essas palavras.",
  /** Formato de conversa (UI-T13, spec 2026-10-02-ui-publica-design §4.8). */
  chat: {
    welcomeTitle: "Respostas só com fontes",
    welcomeText:
      "Pergunte sobre Cuiabá. O CityNews responde com o que as fontes publicaram e mostra de onde veio cada frase.",
    startersLabel: "Perguntas para começar",
    you: "Você",
    youAsked: "Você perguntou:",
    citynews: "CityNews",
    label: "Sua pergunta",
    placeholder: "Pergunte sobre Cuiabá…",
    send: "Enviar pergunta",
    counter: (n: number, max: number) => `${n} de ${max}`,
    steps: { sources: "Buscando fontes", comparing: "Comparando", writing: "Escrevendo" },
    ready: "Resposta pronta.",
    readyRefused: "O CityNews não encontrou fontes suficientes.",
    readyProblem: "Não foi possível responder agora.",
    traditional: "Buscar do jeito tradicional",
    networkTitle: "A conexão caiu antes da resposta",
    networkText: "Confira a internet e tente de novo. A busca tradicional também está à mão.",
    sourcesCount: (n: number) => (n === 1 ? "1 fonte" : `${n} fontes`),
    foundCount: (n: number) => (n === 1 ? "1 fonte encontrada" : `${n} fontes encontradas`),
    panelTitle: "Fontes da resposta",
    panelEmpty: "As fontes da resposta aparecem aqui, numeradas como no texto.",
    historyTitle: "Conversas neste aparelho",
    historyHint: "Ficam só neste aparelho, porque você aceitou a personalização.",
    historyEmpty: "Nenhuma conversa salva ainda.",
    newConversation: "Nova conversa",
    conversationLabel: "Conversa com o CityNews",
  },
  /** Modo simples (sem JavaScript): formulário GET `?q=&modo=simples` respondido no servidor. */
  simpleMode: "simples",
} as const;
