/** Textos de agentes, modelos, prompts e playground (Control Center O10, O11, O12 e O15; P5-T5). */

export const AI_ADMIN_TEXT = {
  // Domínio (mensagens das ações)
  forbidden: "Seu papel não permite esta ação.",
  onlyOperator: "Só a operação de IA cria e propõe versões de prompt.",
  unknownAgent: "Agente desconhecido.",
  bodyRequired: "Escreva o texto do prompt.",
  bodyTooLong: (max: number) => `O prompt passa de ${max} caracteres.`,
  rationaleRequired: "Escreva a justificativa da mudança.",
  noChange: "O texto é igual ao da versão em produção. Nada a propor.",
  promptNotFound: "Versão de prompt não encontrada.",
  notDraft: "Só uma versão em rascunho ou aguardando aprovação pode ser proposta.",
  alreadyPending: "Esta versão já tem um pedido de aprovação pendente.",
  approvalRequired:
    "Publicar exige a aprovação de outra pessoa. Proponha a publicação e peça a aprovação.",
  approvalPending: "Há um pedido pendente. Quem decide aprova em Aprovações.",
  rollbackTargetLive: "Esta versão já está em produção.",
  rollbackTargetNever:
    "Só uma versão que já esteve em produção pode ser restaurada. Proponha uma nova versão.",
  actionFailed: "A ação não pôde ser feita. Confira a situação da versão e tente de novo.",
  rollbackDefaultWhy: (v: number) => `Rollback para a versão ${v}.`,
  rollbackRationale: (v: number, why: string) => `Rollback para a versão ${v}: ${why}`,
  toggleDenied: "Só admin e operação de IA ligam ou desligam um agente.",
  modelNotFound: "Modelo não encontrado.",
  modelInactive: "Este modelo está inativo. Escolha um modelo ativo.",
  inputRequired: "Cole o texto do item de teste.",
  rateLimited: "Muitos testes em pouco tempo. Tente de novo daqui a pouco.",
  playgroundError: {
    timeout: "O modelo demorou demais para responder.",
    provider: "O provedor de IA falhou. Tente de novo.",
    schema: "A saída não seguiu o formato esperado.",
    budget_exceeded: "O orçamento diário deste agente (ou o global) foi atingido.",
    disabled: "A IA está desligada, ou o agente ou o modelo não está disponível.",
    injection:
      "O texto tem instrução embutida e foi recusado antes de chegar ao modelo, como acontece em produção.",
    unknown_agent: "Agente desconhecido.",
  },

  // Agentes (O10)
  agentsTitle: "Agentes de IA",
  agentsIntro:
    "Cada agente tem um modelo, um fallback, um orçamento diário e um prompt em produção. O corte geral da IA fica em Governança.",
  agentsLoading: "Carregando os agentes",
  agentsCaption: "Agentes de IA, com modelo, fallback, orçamento e prompt em produção",
  colAgent: "Agente",
  colFunction: "Função",
  colModel: "Modelo",
  colFallback: "Fallback",
  colBudget: "Orçamento do dia",
  colPrompt: "Prompt em produção",
  colState: "Estado",
  colActions: "Ações",
  noFallback: "Sem fallback",
  noPrompt: "Sem prompt",
  promptVersion: (v: number) => `Versão ${v}`,
  budgetOf: (spent: string, budget: string) => `${spent} de ${budget}`,
  budgetOver: "Orçamento atingido",
  stateOn: "Ligado",
  stateOff: "Desligado",
  turnOff: "Desligar",
  turnOn: "Ligar",
  turnOffNamed: (a: string) => `Desligar o agente ${a}`,
  turnOnNamed: (a: string) => `Ligar o agente ${a}`,
  openPrompts: "Ver prompts",
  openPromptsNamed: (a: string) => `Ver prompts do agente ${a}`,
  toggledOn: (a: string) => `Agente ${a} ligado.`,
  toggledOff: (a: string) =>
    `Agente ${a} desligado. Etapas que dependem dele vão para revisão humana.`,
  readOnly: "Somente leitura para o seu papel.",
  emptyAgentsTitle: "Nenhum agente cadastrado",
  emptyAgentsBody:
    "Os agentes vêm da migration de IA. Rode o banco de novo ou peça ajuda à equipe técnica.",

  // Modelos (O11)
  modelsTitle: "Modelos",
  modelsIntro:
    "Modelos registrados no banco, com custo por mil tokens em reais. Um modelo inativo não é chamado por nenhum agente.",
  modelsLoading: "Carregando os modelos",
  modelsCaption: "Modelos de IA, com custo por mil tokens e estado",
  colModelName: "Modelo",
  colProvider: "Provedor",
  colVersion: "Versão",
  colCostIn: "Custo de entrada (R$ por 1 000 tokens)",
  colCostOut: "Custo de saída (R$ por 1 000 tokens)",
  colMaxTokens: "Máximo de tokens",
  colTemperature: "Temperatura",
  colUsedBy: "Usado por",
  statusActive: "Ativo",
  statusInactive: "Inativo",
  usedByNone: "Nenhum agente",
  notApplicable: "Não se aplica",
  emptyModelsTitle: "Nenhum modelo cadastrado",
  emptyModelsBody: "Os modelos vêm da migration de IA.",

  // Prompts (O12)
  promptsTitle: (agent: string) => `Prompts do agente ${agent}`,
  promptsIntro:
    "Toda mudança vira uma nova versão. Publicar em produção exige a aprovação de outra pessoa, com justificativa.",
  promptsLoading: "Carregando os prompts",
  promptsBack: "Voltar aos agentes",
  promptsNotFoundTitle: "Agente não encontrado",
  promptsNotFoundBody: "Não há agente com este identificador.",
  productionTitle: "Em produção",
  productionLine: (v: number, who: string | null, when: string | null) =>
    who && when ? `Versão ${v}, aprovada por ${who} em ${when}.` : `Versão ${v}.`,
  productionSeed: (v: number) => `Versão ${v}, publicada pela migration de IA.`,
  productionNone: "Este agente não tem prompt em produção. Ele fica desligado até haver um.",
  promptBodyLabel: "Texto do prompt em produção",
  editorTitle: "Nova versão",
  editorIntro:
    "Edite a partir da versão em produção. As mudanças aparecem abaixo, palavra por palavra.",
  editorBodyLabel: "Texto do prompt",
  editorBodyHint: (max: number) =>
    `Até ${max} caracteres. O texto é do agente, não do conteúdo coletado: nunca cole aqui texto de fontes.`,
  editorWhyLabel: "Justificativa",
  editorWhyHint: "O que muda e por quê. Vai para o pedido de aprovação e para o histórico.",
  diffTitle: "Mudanças em relação à produção",
  diffCaption: "Diferença entre o prompt em produção e o texto editado",
  diffNone: "Sem mudança em relação à produção.",
  saveDraft: "Salvar rascunho",
  saveAndPropose: "Salvar e propor publicação",
  saving: "Salvando",
  draftSaved: (v: number) => `Versão ${v} salva como rascunho.`,
  proposed: (v: number) => `Versão ${v} proposta. Outra pessoa precisa aprovar em Aprovações.`,
  proposeExisting: "Propor publicação",
  proposeExistingNamed: (v: number) => `Propor publicação da versão ${v}`,
  approveAndPublish: "Aprovar e publicar",
  approveAndPublishNamed: (v: number) => `Aprovar e publicar a versão ${v}`,
  published: (v: number) => `Versão ${v} em produção.`,
  cannotEdit: "Só a operação de IA cria versões. Você pode acompanhar e aprovar.",
  waitingApproval: "Aguarda a aprovação de outra pessoa.",
  goApprovals: "Ir para Aprovações",
  historyTitle: "Histórico de versões",
  historyCaption: "Versões do prompt, da mais nova para a mais antiga",
  colVer: "Versão",
  colStatus: "Situação",
  colAuthor: "Autoria",
  colApprover: "Aprovada por",
  colCreated: "Criada em",
  colWhy: "Justificativa",
  colCompare: "Comparar",
  compareLink: "Comparar com a produção",
  compareNamed: (v: number) => `Comparar a versão ${v} com a produção`,
  compareTitle: (v: number, prod: number | null) =>
    prod === null ? `Versão ${v}` : `Versão ${v} em relação à versão ${prod} em produção`,
  rollback: "Restaurar",
  rollbackNamed: (v: number) => `Restaurar a versão ${v} como nova versão`,
  rollbackNote:
    "Restaurar cria uma nova versão com o texto desta e pede aprovação, como qualquer publicação.",
  rollbackWhyLabel: "Justificativa do rollback",
  rollbackDone: (v: number, from: number) =>
    `Versão ${v} criada com o texto da versão ${from} e enviada para aprovação.`,
  statusDraft: "Rascunho",
  statusPending: "Aguarda aprovação",
  statusProduction: "Em produção",
  statusArchived: "Arquivada",
  statusReverted: "Revertida",
  statusRejected: "Recusada",
  rollbackOf: (v: number) => `Restaura a versão ${v}`,
  unknownPerson: "Pessoa removida",
  systemAuthor: "Migration de IA",
  nobody: "Ninguém",
  errorTitle: "Não foi possível carregar",
  errorBody:
    "O banco não respondeu agora. Nenhuma mudança foi perdida. Tente de novo em instantes.",
  retry: "Tentar de novo",

  // Playground (O15)
  testsTitle: "Playground de testes",
  testsIntro:
    "Teste um agente com uma versão de prompt e um modelo à sua escolha. O texto passa pela mesma sanitização e pelos mesmos delimitadores de dados da produção. Nada é publicado, e o custo entra no orçamento do dia.",
  testsLoading: "Carregando o playground",
  testAgent: "Agente",
  testPrompt: "Versão do prompt",
  testModel: "Modelo",
  testInput: "Item de teste",
  testInputHint: "Cole um texto fictício ou de teste. Até 6 000 caracteres são enviados.",
  testRun: "Rodar teste",
  testRunning: "Rodando o teste",
  testPromptOption: (v: number, status: string) => `Versão ${v} (${status})`,
  resultTitle: "Resultado",
  resultInputTitle: "Entrada sanitizada",
  resultOutputTitle: "Saída",
  resultValid: "Saída válida no schema do agente.",
  resultInvalid: "Saída fora do schema do agente.",
  resultCost: "Custo",
  resultLatency: "Latência",
  resultProvider: "Provedor",
  providerFake: "falso (sem rede)",
  providerReal: "OpenRouter",
  resultBudgetNote: "Este teste entrou no gasto do dia do agente.",
  resultEmpty:
    "Rode um teste para ver a entrada sanitizada, a saída, a validade, o custo e a latência.",
  resultFailed: "O teste não terminou",
  noPromptVersions: "Este agente ainda não tem versões de prompt.",
  noActiveModels: "Nenhum modelo ativo.",
  ms: (n: number) => `${n.toLocaleString("pt-BR")} ms`,
  brl: (n: number) =>
    n.toLocaleString("pt-BR", {
      style: "currency",
      currency: "BRL",
      minimumFractionDigits: 2,
      maximumFractionDigits: 6,
    }),
  brlShort: (n: number) => n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }),
} as const;

export type PlaygroundErrorKey = keyof typeof AI_ADMIN_TEXT.playgroundError;

export const PROMPT_STATUS_LABEL: Record<string, string> = {
  draft: AI_ADMIN_TEXT.statusDraft,
  pending: AI_ADMIN_TEXT.statusPending,
  production: AI_ADMIN_TEXT.statusProduction,
  archived: AI_ADMIN_TEXT.statusArchived,
  reverted: AI_ADMIN_TEXT.statusReverted,
};

/** Nomes de agente para a tela (id técnico entre parênteses na tabela). */
export const AGENT_LABEL: Record<string, string> = {
  classify: "Classificação",
  locate: "Localidade",
  verify: "Verificação de fontes",
  write: "Redação do rascunho",
  answer: "Busca com IA",
  image: "Ilustração",
  aggregate_summary: "Resumo de agregado",
  source_profiler: "Perfil de fonte",
  embed: "Embeddings",
};
export const agentLabel = (id: string): string => AGENT_LABEL[id] ?? id;
