/**
 * Control Center · Recomendação (O17) e testes A/B (O18), P5-T7. Sem dado pessoal: o leitor
 * aparece só como apelido (hash), nunca com o id anônimo.
 */
import type { WeightKey } from "@/lib/ranking/types";

export const WEIGHT_LABEL: Record<WeightKey, string> = {
  popularity: "Popularidade",
  individual: "Afinidade individual",
  recency: "Atualização recente",
  engagement: "Engajamento",
  operational: "Saúde operacional",
  diversity: "Diversidade",
};

export const WEIGHT_HINT: Record<WeightKey, string> = {
  popularity: "Alcance da fonte entre os leitores, por percentil.",
  individual: "Só com Personalização ligada pelo leitor; sem ela vale 0.",
  recency: "Quão recentes são os itens que a fonte publica.",
  engagement: "Cliques, salvamentos, compartilhamentos e retorno.",
  operational: "Coleta saudável e frequência de atualização.",
  diversity: "Quanto a fonte amplia o que o leitor já vê.",
};

export const REC_TEXT = {
  title: "Recomendação de fontes",
  intro:
    "Como as fontes são ordenadas para os leitores: pesos, teto de concentração, campanhas de descoberta e testes A/B. Mudar pesos exige a aprovação de outra pessoa.",
  loading: "Carregando o painel de recomendação",
  errorTitle: "Não foi possível carregar o painel",
  errorBody: "O banco não respondeu. Nada foi alterado. Tente de novo em instantes.",
  retry: "Tentar de novo",
  forbidden: "Seu papel não permite esta ação.",
  invalid: "Confira os campos e tente de novo.",

  /* painel */
  panelTitle: "Diversidade e concentração",
  panelWindow: "Últimos 7 dias",
  kpiVersion: "Versão em uso",
  kpiDiversity: "Índice de diversidade",
  kpiTop3: "Concentração das 3 maiores fontes",
  kpiPersonalization: "Eventos com Personalização ativa",
  kpiAccounts: "Eventos de contas",
  kpiExperiments: "Testes em andamento",
  kpiCtr: "CTR das recomendações",
  kpiDismiss: "Ocultações",
  noEvents: "Sem eventos no período",
  diversityHelp:
    "1 menos a soma dos quadrados das fatias: 0 é uma fonte só, perto de 1 é bem distribuído.",
  alertTitle: "Concentração alta",
  alertBody: (pct: string) =>
    `As 3 maiores fontes concentram ${pct} dos cliques, acima de 50%. Considere aumentar o peso de diversidade ou reduzir o teto.`,
  okBody: (pct: string) =>
    `As 3 maiores fontes concentram ${pct} dos cliques, dentro do limite de 50%.`,
  sharesTitle: "Participação por fonte",
  sharesCaption: "Participação de cada fonte nos cliques dos últimos 7 dias",
  sharesBasisClicks: "cliques",
  sharesBasisSessions: "sessões (não houve cliques no período)",
  sharesEmpty: "Ainda não há cliques nem sessões por fonte nos últimos 7 dias.",
  sharesSummary: (top: string, n: number, idx: string, basis: string) =>
    `${n} fontes com ${basis}. Maior participação: ${top}. Índice de diversidade ${idx}.`,
  colSource: "Fonte",
  colShare: "Participação",
  colCount: "Total",
  byListTitle: "Cliques por lista",
  dismissTitle: "Ocultações por motivo",
  listEmpty: "Nenhum registro no período.",
  colList: "Lista",
  colReason: "Motivo",
  colQty: "Quantidade",

  /* pesos */
  weightsTitle: "Pesos do score",
  weightsIntro:
    "Os seis pesos precisam somar 1,00. A proposta vira uma versão nova e só entra em vigor depois que outra pessoa aprovar em Aprovações.",
  sumLabel: "Soma dos pesos",
  sumOk: (sum: string) => `Soma ${sum}: válida.`,
  sumBad: (sum: string) => `Soma ${sum}: precisa ser 1,00 para salvar.`,
  normalize: "Ajustar proporcionalmente para 1,00",
  reset: "Voltar aos pesos em vigor",
  capLabel: "Teto por fonte",
  capHint: "Fatia máxima de uma fonte numa lista.",
  everyLabel: "Descoberta a cada",
  everyHint: "1 fonte nova a cada N posições em Recomendadas.",
  justificationLabel: "Justificativa",
  justificationHint: "Explique por que mudar. Fica registrada no pedido de aprovação.",
  propose: "Propor novos pesos",
  proposing: "Enviando",
  unchanged: "Nada mudou em relação à versão em vigor.",
  readOnly: "Seu papel permite ver os pesos, não propô-los.",
  proposedOk: (version: string) => `Versão ${version} proposta. Falta a aprovação de outra pessoa.`,
  goApprovals: "Ver aprovações",
  individualNote: "Sem Personalização, o peso individual vale 0 e os demais são renormalizados.",
  valueText: (label: string, pct: string) => `${label}: ${pct}`,
  historyTitle: "Histórico de pesos",
  historyCaption: "Versões de pesos, da mais nova para a mais antiga",
  colVersion: "Versão",
  colStatus: "Situação",
  colWeights: "Pesos",
  colProposer: "Proposta por",
  colApprover: "Aprovada por",
  colCreated: "Criada em",
  statusActive: "Em vigor",
  statusPending: "Aguardando aprovação",
  statusRetired: "Aposentada",
  statusDraft: "Proposta sem pedido",
  nobody: "Ninguém",
  unknownPerson: "Pessoa removida",
  noHistory: "Nenhuma versão de pesos registrada.",
  compact: (w: Record<WeightKey, number>) =>
    `pop ${w.popularity.toFixed(2)} · ind ${w.individual.toFixed(2)} · rec ${w.recency.toFixed(2)} · eng ${w.engagement.toFixed(2)} · ope ${w.operational.toFixed(2)} · div ${w.diversity.toFixed(2)}`,
  dp3Title: "Score editorial (rec-v2)",
  dp3Body:
    "O score editorial das fontes continua fora do ranking (decisão pendente DP-3). Entrar exigiria uma versão rec-v2 com componente novo, proposta e aprovada por duas pessoas. Nada aqui a ativa.",

  /* campanhas e destaques */
  curationTitle: "Destaques e campanhas",
  curationIntro: "Fontes fixadas, excluídas e com destaque local vêm do cadastro de cada fonte.",
  curationCaption: "Fontes com regra de recomendação",
  colFlags: "Regras",
  flagPinned: "Fixada no topo",
  flagExcluded: "Excluída da recomendação",
  flagLocal: "Destaque local",
  curationEmpty: "Nenhuma fonte com regra de recomendação.",
  editSource: (name: string) => `Editar regras de ${name}`,
  edit: "Editar",
  campaignsTitle: "Campanhas de descoberta",
  campaignsCaption: "Campanhas de descoberta e o que renderam no período",
  campaignsEmpty: "Nenhuma campanha criada.",
  campaignsNote:
    "A campanha registra e mede o esforço de descoberta. A cota ainda não altera o ranking: o algoritmo segue com 1 descoberta a cada 5.",
  colCampaign: "Campanha",
  colSources: "Fontes",
  colPeriod: "Período",
  colQuota: "Cota",
  colAudience: "Público",
  colResult: "Resultado",
  colState: "Situação",
  campaignPlanned: "Agendada",
  campaignRunning: "Em andamento",
  campaignEnded: "Encerrada",
  resultText: (clicks: number, sessions: number) => `${clicks} cliques · ${sessions} sessões`,
  quotaText: (pct: number) => `${pct}%`,
  period: (a: string, b: string) => `${a} a ${b}`,
  audience: { todos: "Todos os leitores", anonimos: "Só anônimos", contas: "Só contas" },
  newCampaign: "Nova campanha",
  campName: "Nome da campanha",
  campSources: "Fontes (uma por linha, pelo identificador)",
  campSourcesHint: "Exemplo: folha-do-cerrado",
  campStart: "Início",
  campEnd: "Fim",
  campQuota: "Cota de vagas (%)",
  campAudience: "Público",
  campCreate: "Criar campanha",
  campCreated: "Campanha criada.",
  campEnd_: "Encerrar",
  campEndLabel: (name: string) => `Encerrar a campanha ${name}`,
  campEndedOk: "Campanha encerrada.",
  campUnknownSource: (slug: string) => `Fonte desconhecida ou fora do ar: ${slug}.`,
  campDates: "O fim precisa ser depois do início, em até 90 dias.",
  campNameRequired: "Dê um nome de 3 a 120 letras.",
  campSourcesRequired: "Informe de 1 a 10 fontes.",

  /* testes A/B */
  testsTitle: "Testes A/B",
  testsCaption: "Testes A/B de pesos",
  testsEmpty: "Nenhum teste criado.",
  testsIntro:
    "Cada variante usa uma versão de pesos. O leitor cai sempre na mesma variante, sorteada a partir do id anônimo com hash estável; só quem ligou a Personalização entra na medição.",
  newTest: "Novo teste",
  testName: "Nome do teste",
  testHypothesis: "Hipótese (opcional)",
  testVariant: (n: number) => `Variante ${n}: versão de pesos`,
  testSplit: (n: number) => `Divisão da variante ${n} (%)`,
  testSplitSum: (sum: number) => `Divisão soma ${sum}%: precisa ser 100%.`,
  testSplitOk: "Divisão soma 100%.",
  testCreate: "Criar teste",
  testCreated: "Teste criado como rascunho.",
  testNameRequired: "Dê um nome de 3 a 120 letras.",
  testVariantsInvalid: "Escolha versões de pesos aprovadas e diferentes para as variantes.",
  testSplitInvalid: "A divisão precisa somar 100%, com cada variante acima de 0%.",
  addVariant: "Adicionar variante",
  removeVariant: "Remover a última variante",
  colTest: "Teste",
  colVariants: "Variantes",
  colSplit: "Divisão",
  colWinner: "Vencedora",
  testDraft: "Rascunho",
  testRunning: "Em andamento",
  testEnded: "Encerrado",
  open: "Abrir",
  openLabel: (name: string) => `Abrir o teste ${name}`,
  control: "controle",
  backToPanel: "Voltar à recomendação",

  /* detalhe do teste */
  testNotFoundTitle: "Teste não encontrado",
  testNotFoundBody: "O teste não existe ou você não tem acesso a ele.",
  /** `index` é a posição (0 = controle); a tela conta a partir de 1. */
  variantLabel: (index: number, control: boolean) =>
    `Variante ${index + 1}${control ? " (controle)" : ""}`,
  weightsVersion: (v: string) => `Pesos ${v}`,
  metricsTitle: "Métricas por variante",
  metricsCaption: "Métricas por variante do teste",
  metricsEmpty: "Sem eventos de leitores na janela do teste. Rascunho ou início recente.",
  metricsNote:
    "Medido só entre leitores com Personalização ligada (sem consentimento não há id anônimo). Os números são contagens por variante; ninguém é identificado.",
  metricsTruncated: "Amostra limitada aos primeiros 20 mil registros de leitor por fonte.",
  colVariant: "Variante",
  colReaders: "Leitores",
  colViews: "Fontes vistas",
  colClicks: "Cliques",
  colCtr: "CTR",
  colReturn: "Retorno em outro dia",
  colDiversity: "Diversidade",
  colDismiss: "Ocultação",
  colSignificance: "Significância do CTR",
  significant: (lift: string) => `Diferença significativa (${lift} sobre o controle)`,
  notSignificant: "Sem diferença significativa",
  noControl: "Base de comparação",
  metricsSummary: (parts: string) => `Resumo: ${parts}`,
  chartLabel: "CTR por variante",
  chartSummary: (parts: string) => `CTR por variante: ${parts}.`,
  start: "Iniciar teste",
  startedOk: "Teste iniciado.",
  end: "Encerrar teste",
  endWinner: "Variante vencedora",
  endNone: "Sem vencedora",
  endedOk: "Teste encerrado.",
  promote: "Promover a vencedora",
  promoteHint:
    "Promover pede a aprovação de outra pessoa para tornar os pesos da variante vencedora os pesos em vigor.",
  promotedOk: (version: string) =>
    `Pedido de aprovação enviado para os pesos ${version}. Falta a decisão de outra pessoa.`,
  promoteNeedsJustification: "Escreva a justificativa da promoção.",
  runningState: "Em andamento desde",
  endedState: "Encerrado em",
  draftState: "Ainda não iniciado",
  wrongState: "O teste não está no estado esperado para esta ação.",

  /* por que esta recomendação */
  whyTitle: "Por que esta recomendação",
  whyIntro:
    "Cole um id anônimo para ver como o score de cada fonte se compõe para aquele leitor. O id não é gravado nem exibido: a tela mostra só um apelido.",
  whyLabel: "Id anônimo do leitor",
  whyHint: "Formato de id (uuid) copiado do evento. Ele não aparece na página.",
  whyButton: "Explicar recomendações",
  whyWorking: "Calculando",
  whyInvalid: "Informe um id anônimo válido (uuid).",
  whyForbidden: "Seu papel não permite esta consulta.",
  whyError: "Não foi possível calcular agora. Tente de novo.",
  whyResultTitle: (alias: string) => `Recomendações para ${alias}`,
  whyNoConsent:
    "O painel não mostra a afinidade individual: o CityNews não guarda o consentimento vigente do leitor no servidor (ao retirar a Personalização, os eventos novos deixam de trazer o id). O peso individual vale 0 e o score usa só sinais gerais, como para qualquer visitante anônimo.",
  whyConsent:
    "Este leitor ligou a Personalização: o componente individual entra no score, com o peso da versão em vigor.",
  whyVersion: (v: string) => `Versão de pesos: ${v}`,
  whyCaption: (alias: string) => `Componentes do score das fontes recomendadas para ${alias}`,
  whyEmpty: "Nenhuma fonte elegível para recomendar.",
  colPosition: "Posição",
  colScore: "Score",
  colWhy: "Justificativa",
  colDiscovery: "Descoberta",
  yes: "Sim",
  no: "Não",
  componentCell: (value: string, weight: string) => `${value} × ${weight}`,
  componentNote: "Cada célula mostra o sinal (0 a 1) multiplicado pelo peso em uso.",
  close: "Limpar resultado",
} as const;
