/**
 * Textos de A09 · Notificações no Estúdio (spec 2026-09-28 §10): abas, estados, erros das
 * ações, faixas do cabeçalho e o diálogo de publicação (E06).
 */
import type { PushKind, SendStatus } from "@/lib/push/types";

export const PUSH_ADMIN_TEXT = {
  title: "Notificações",
  intro:
    "Avisos no celular e no computador de quem ativou. Urgente e Destaque passam por aprovação registrada; quem pode aprovar envia na hora.",
  sectionNav: "Seções de Notificações",
  tabs: {
    new: "Novo envio",
    queue: "Fila e aprovações",
    history: "Histórico",
    settings: "Configurações",
  },
  funnelLink: "Funil do app",
  banners: {
    paused: (by: string, at: string, reason: string) =>
      `Envios pausados por ${by} às ${at}: ${reason}`,
    pausedShort: "Envios pausados",
    pending: (n: number) =>
      n === 1 ? "1 pedido aguarda sua aprovação" : `${n} pedidos aguardam sua aprovação`,
    pendingLink: "Ver a fila",
    vapidMissing: (names: string[]) =>
      `Push indisponível: configure ${names.join(", ")} na Vercel.`,
    vapidOk: "Chaves VAPID configuradas",
  },
  followNote: "Avisos do que o leitor segue são automáticos e não passam por aqui.",
  kind: {
    urgent: "Urgente",
    highlight: "Destaque da redação",
    follow: "Do que o leitor segue",
  } satisfies Record<PushKind, string>,
  status: {
    pending_approval: "Aguardando aprovação",
    scheduled: "Agendado",
    queued: "Na fila de envio",
    dispatching: "Enviando",
    sent: "Enviado",
    paused: "Pausado",
    cancelled: "Cancelado",
    rejected: "Recusado",
    expired: "Expirado",
  } satisfies Record<SendStatus, string>,
  audience: {
    all: (kind: PushKind) =>
      kind === "urgent"
        ? "Todos que ativaram Urgentes"
        : kind === "highlight"
          ? "Todos que ativaram Destaques"
          : "Quem segue a matéria",
    section: (name: string) => `Editoria: ${name}`,
    bairro: (name: string) => `Bairro: ${name}`,
  },
  reach: {
    fewer: "menos de 20",
    about: (n: number) => `cerca de ${n}`,
    subs: (n: number) => (n === 0 ? "menos de 20 inscrições" : `cerca de ${n} inscrições`),
    label: "Alcance estimado",
    loading: "Calculando o alcance…",
    unavailable: "Alcance indisponível agora.",
  },
  approval: {
    pending: "Pendente",
    by: (name: string, at: string) => `Aprovado por ${name} às ${at}`,
  },
  errors: {
    forbidden: "Sua conta não tem permissão para esta ação.",
    not_pending: "Este pedido já foi decidido.",
    invalid: "Revise os campos destacados.",
    article_invalid: "Só matéria publicada e não patrocinada vira aviso.",
    national_scope:
      "Notícia nacional sem comoção não vira urgente. Urgente é só para Cuiabá e Mato Grosso.",
    conflict: "O pedido mudou depois que você abriu. Recarregue e tente de novo.",
    unavailable: "Não foi possível concluir agora. Tente de novo em instantes.",
    rateLimited: "Você fez muitas ações na última hora. Tente de novo mais tarde.",
    reasonRequired: "Informe o motivo.",
    justificationRequired: "Justificativa obrigatória para urgente.",
    typePause: "Digite PAUSAR para confirmar.",
    schedule: {
      urgent_now_only: "Urgente só sai agora.",
      past: "O horário já passou.",
      too_far: "Agende no máximo 7 dias à frente.",
      quiet: "Fora do silêncio: escolha um horário entre 7h e 22h.",
      invalid: "Data ou hora inválida.",
    },
  },
  done: {
    requested: "Pedido criado. Aguardando aprovação de quem pode aprovar avisos.",
    sentNow: "Aplicado. O aviso entrou na fila de envio e fica registrado no histórico.",
    policyRejected: (reason: string) => `Recusado pela política de avisos: ${reason}`,
    scheduledNow: "Aplicado. O aviso sai no horário agendado e fica registrado no histórico.",
    requestedPaused: "Pedido criado. Envios pausados: o pedido fica na fila até a retomada.",
    approved: "Pedido aprovado",
    approvedScheduled: "Pedido aprovado. Sai no horário agendado.",
    rejected: "Pedido recusado",
    cancelled: "Envio cancelado",
    paused: "Envios pausados. Tudo, inclusive os automáticos, fica parado até a retomada.",
    resumeRequested: "Retomada pedida. Quem tem permissão de aprovar precisa confirmar.",
    resumedNow: "Envios retomados. Fica registrado no histórico.",
    resumed: "Envios retomados",
    settingsSaved: "Configurações salvas",
  },
  pauseWord: "PAUSAR",
} as const;

/** Aba 1 · Novo envio (spec §10.2). */
export const NEW_PUSH_TEXT = {
  title: "Novo envio",
  kind: "Tipo",
  kindHint: {
    urgent: "Chega mesmo no silêncio; conta no limite diário. Só admin ou editor-chefe pede.",
    highlight: "Sai fora do silêncio; agora ou agendado em até 7 dias.",
  },
  article: "Matéria",
  articleHint: "Busque pelo título entre as publicadas e não patrocinadas.",
  articleResults: "Matérias encontradas",
  articleNone: "Nenhuma matéria publicada com esse título.",
  articleSearching: "Buscando…",
  articleChosen: "Matéria escolhida",
  articleChange: "Trocar matéria",
  articleRequired: "Escolha uma matéria.",
  articleUnpublished: "Se a matéria for despublicada, o envio é cancelado.",
  publishedAt: (when: string) => `Publicada ${when}`,
  template: "Modelo de texto",
  templateNone: "Sem modelo (título e linha fina da matéria)",
  titleField: "Título",
  bodyField: "Texto",
  counter: (n: number, max: number) => `${n} de ${max}`,
  overLimit: (max: number) => `Use até ${max} caracteres.`,
  required: "Preencha este campo.",
  preview: "Prévia",
  previewOf: {
    android: "Prévia no Android",
    iphone: "Prévia no iPhone",
    desktop: "Prévia no computador",
  },
  previewNote: "Cortes aproximados de cada plataforma; o rótulo de origem vai na frente do texto.",
  previewApp: "CityNews Cuiabá",
  previewNow: "agora",
  audience: "Público",
  audienceAll: (kind: "urgent" | "highlight") =>
    kind === "urgent" ? "Todos que ativaram Urgentes" : "Todos que ativaram Destaques",
  audienceSegment: "Segmento",
  segmentType: "Tipo de segmento",
  segmentSection: "Editoria",
  segmentBairro: "Bairro",
  segmentHint: "Conta só inscrições que seguem o alvo e ligaram este tipo de aviso.",
  when: "Quando",
  now: "Agora",
  schedule: "Agendar",
  urgentNowOnly: "Urgente só sai agora.",
  at: "Data e hora (fuso de Cuiabá)",
  atHint: "Até 7 dias à frente, entre 7h e 22h.",
  justification: "Justificativa",
  justificationHint: "Obrigatória para urgente (até 300 caracteres). Fica no registro do pedido.",
  submit: "Enviar para aprovação",
  sending: "Enviando…",
  pausedNotice: "Envios pausados: o pedido fica na fila até a retomada.",
  queueLink: "Ver a fila",
  failed: "Não foi possível criar o pedido. Revise os campos.",
} as const;

/** Aba 4 · Configurações (spec §10.5). */
export const PUSH_SETTINGS_TEXT = {
  title: "Configurações",
  limits: "Limites do leitor",
  dailyLimit: "Limite diário padrão",
  dailyLimitHint: "1 a 3 avisos por dia. Também é o teto do que o leitor escolhe.",
  quietStart: "Início do silêncio",
  quietEnd: "Fim do silêncio",
  quietHint: "Sempre contém 22h–7h.",
  hour: (h: number) => `${h}h`,
  templates: "Modelos de texto",
  templatesHint: "Até 20 modelos. Use {titulo} e {linha_fina} no lugar do texto da matéria.",
  templatesEmpty: "Nenhum modelo ainda.",
  addTemplate: "Adicionar modelo",
  removeTemplate: (name: string) => `Remover modelo ${name || "sem nome"}`,
  templateName: "Nome",
  templateTitle: "Título",
  templateBody: "Texto",
  templateN: (i: number) => `Modelo ${i}`,
  reason: "Motivo da alteração (opcional)",
  save: "Salvar configurações",
  saving: "Salvando…",
  pause: {
    section: "Contingência",
    trigger: "Pausar todos os envios",
    title: "Pausar todos os envios?",
    body: "Vale na hora para tudo: urgentes, destaques, automáticos e agendados. Nada sai até a retomada ser aprovada.",
    reason: "Motivo",
    confirmLabel: "Digite PAUSAR para confirmar",
    mismatch: "Digite exatamente PAUSAR.",
    confirm: "Pausar envios",
    cancel: "Cancelar",
  },
  resume: {
    trigger: "Retomar envios",
    title: "Retomar envios?",
    body: "Quem tem permissão de aprovar retoma na hora; sem essa permissão, fica um pedido de retomada. Tudo fica registrado no histórico; agendados vencidos há mais de 1 h expiram.",
    reason: "Motivo",
    confirm: "Pedir retomada",
    pending: (name: string) =>
      `Retomada pedida por ${name}. Quem tem permissão de aprovar precisa confirmar.`,
    pendingOwn: "Você pediu a retomada. Quem tem permissão de aprovar precisa confirmar.",
    approve: "Aprovar retomada",
  },
  vapid: {
    section: "Configuração técnica",
    ok: "Chaves VAPID configuradas",
    missing: (names: string[]) => `Push indisponível: configure ${names.join(", ")} na Vercel.`,
  },
} as const;

export type PushAdminErrorKey = keyof Pick<
  typeof PUSH_ADMIN_TEXT.errors,
  | "forbidden"
  | "not_pending"
  | "invalid"
  | "article_invalid"
  | "national_scope"
  | "conflict"
  | "unavailable"
>;

/** Aba 2 · Fila e aprovações (spec §10.3). */
export const PUSH_QUEUE_TEXT = {
  title: "Fila e aprovações",
  intro: "Pedidos aguardando decisão e envios ainda em andamento. A lista atualiza a cada 10 s.",
  empty: "Nenhum pedido na fila.",
  emptyHint: "Pedidos novos aparecem aqui até serem enviados, recusados ou expirarem.",
  countChanged: (n: number) => (n === 1 ? "1 item na fila" : `${n} itens na fila`),
  columns: {
    kind: "Tipo",
    article: "Matéria",
    title: "Título",
    audience: "Público e alcance",
    requested: "Pedido por",
    approval: "Aprovação",
    scheduled: "Agendado para",
    status: "Estado",
    actions: "Ações",
  },
  reach: (n: number | null) =>
    n === null ? "" : n === 0 ? "menos de 20 inscrições" : `cerca de ${n} inscrições`,
  now: "Agora",
  approve: (title: string) => `Aprovar ${title}`,
  reject: (title: string) => `Recusar ${title}`,
  cancel: (title: string) => `Cancelar ${title}`,
  review: "Revisar",
  dialog: {
    title: "Revisar pedido de aviso",
    preview: "Prévia",
    kind: "Tipo",
    article: "Matéria",
    audience: "Público",
    when: "Quando",
    requestedBy: "Pedido por",
    justification: "Justificativa",
    noJustification: "Sem justificativa",
    approve: "Aprovar",
    reject: "Recusar",
    rejectReason: "Motivo da recusa",
    rejectRequired: "Informe o motivo da recusa.",
    confirmReject: "Confirmar recusa",
    cancel: "Cancelar envio",
    cancelReason: "Motivo do cancelamento",
    cancelRequired: "Informe o motivo.",
    confirmCancel: "Confirmar cancelamento",
    close: "Fechar",
  },
} as const;

/** Aba 3 · Histórico (spec §10.4). */
export const PUSH_HISTORY_TEXT = {
  title: "Histórico",
  intro: "Um registro por envio, inclusive os automáticos do que o leitor segue.",
  filters: { period: "Período", kind: "Tipo", status: "Estado", apply: "Filtrar", all: "Todos" },
  periods: { 7: "7 dias", 30: "30 dias", 90: "90 dias", tudo: "Tudo" },
  export: "Exportar CSV",
  exportNote: "O CSV não tem nenhum dado de inscrição.",
  ctrNote: "Recebidos, tocados e CTR contam só entre quem permite métricas.",
  empty: "Sem envios no período.",
  emptyHint: "Amplie o período ou tire os filtros.",
  columns: {
    date: "Data",
    kind: "Tipo",
    article: "Matéria",
    requestedBy: "Pedido por",
    approvedBy: "Aprovado por",
    audience: "Público",
    targets: "Alvos",
    sent: "Enviados",
    accepted: "Aceitos",
    failed: "Falhas",
    removed: "Removidas",
    skipped: "Puladas",
    delivered: "Recebidos",
    clicked: "Tocados",
    ctr: "CTR",
    status: "Estado",
  },
  system: "Sistema",
  none: "—",
  page: (p: number, total: number) => `Página ${p} de ${total}`,
  prev: "Anterior",
  next: "Próxima",
  detail: {
    back: "Voltar ao histórico",
    requestedBy: (name: string) => `Pedido por ${name}`,
    approvedBy: (name: string, at: string) => `Aprovado por ${name} às ${at}`,
    timeline: "Linha do tempo",
    numbers: "Números do envio",
    skips: "Puladas por motivo",
    failures: "Falhas por código",
    breakdown: "Por classe de aparelho e navegador",
    breakdownChart: "Recebidos e tocados por aparelho e navegador",
    noSkips: "Nenhuma pulada.",
    noFailures: "Nenhuma falha.",
    noBreakdown: "Sem recebidos ainda.",
    labels: {
      requested: "Pedido",
      approved: "Aprovação",
      rejected: "Recusado",
      cancelled: "Cancelado",
      expired: "Expirado",
      started: "Início do envio",
      finished: "Fim do envio",
      paused: "Pausado",
    },
    skipReason: {
      pref: "preferência do leitor",
      limit: "limite diário",
      quiet: "silêncio",
      duplicate: "já recebeu a matéria",
      coalesced: "juntado a outro aviso",
      expired: "fora do prazo",
      gone: "inscrição removida",
    } as Record<string, string>,
    device: {
      mobile: "Celular",
      tablet: "Tablet",
      desktop: "Computador",
      other: "Outro",
    } as Record<string, string>,
    browser: {
      chrome: "Chrome",
      safari: "Safari",
      firefox: "Firefox",
      edge: "Edge",
      samsung: "Samsung Internet",
      other: "Outro",
    } as Record<string, string>,
    columns: {
      device: "Aparelho",
      browser: "Navegador",
      sent: "Enviados",
      delivered: "Recebidos",
      clicked: "Tocados",
    },
    summary: (delivered: number, clicked: number, top: string | null) =>
      delivered === 0
        ? "Nenhum recebido registrado."
        : `${delivered} recebidos e ${clicked} tocados${top ? `; a maior parte em ${top}` : ""}.`,
    notFound: "Envio não encontrado",
    notFoundText: "O envio não existe ou você não tem acesso a ele.",
  },
} as const;

/** Funil do app (spec §10.6). */
export const FUNNEL_TEXT = {
  title: "Funil do app",
  intro: "Do convite de instalação ao toque no aviso, em eventos de quem permite métricas.",
  notice: "Contagens de eventos de quem permite métricas; não são pessoas.",
  filters: {
    period: "Período",
    custom: "Personalizado",
    from: "De",
    to: "Até",
    device: "Classe de aparelho",
    browser: "Navegador",
    all: "Todos",
    apply: "Filtrar",
  },
  periods: { 7: "7 dias", 30: "30 dias", 90: "90 dias" },
  devices: { mobile: "Celular", tablet: "Tablet", desktop: "Computador" },
  browsers: {
    chrome: "Chrome",
    safari: "Safari",
    firefox: "Firefox",
    edge: "Edge",
    samsung: "Samsung Internet",
    other: "Outro",
  },
  chart: "Funil do app por etapa",
  columns: { stage: "Etapa", n: "Eventos", pct: "% da anterior" },
  empty: "Sem dados no período.",
  emptyHint: "Amplie o período ou tire os filtros.",
  side: {
    outside: "Fora do convite",
    outInstall: "Instalações pelo navegador",
    outPermission: "Permissões dadas em Alertas",
    denied: "Negadas",
    deniedHint: "Permissões negadas no navegador.",
    sentTotal: "Enviados no total",
    sentTotalHint: "Todas as inscrições; a base do funil é só quem permite métricas.",
    active: "Inscrições ativas por navegador",
    activeNone: "Nenhuma inscrição ativa.",
  },
  none: "—",
} as const;
