/*
 * Textos do portal público (P1), parte "article". `portal.ts` reexporta tudo; os componentes do
 * navegador importam daqui para levar só o que usam (B-018).
 */

/** Informar problema (P03, ReportProblemForm). */
export const REPORT = {
  open: "Informar problema",
  title: "Informar problema nesta matéria",
  intro: "Não precisa de conta. A redação lê cada aviso.",
  kindLegend: "O que está errado?",
  kinds: {
    wrong_info: "Informação errada",
    broken_link: "Link quebrado",
    image: "Problema com a imagem",
    right_of_reply: "Direito de resposta",
    other: "Outro problema",
  },
  message: "Conte o que viu (opcional)",
  messageHint: "Até 1.000 caracteres. Exemplo: o horário certo é 19h, não 18h.",
  contact: "Seu e-mail para resposta (opcional)",
  contactPlaceholder: "voce@exemplo.com",
  submit: "Enviar",
  sending: "Enviando…",
  kindRequired: "Escolha o tipo de problema. Exemplo: Informação errada.",
  invalidEmail: "Confira o e-mail digitado. Exemplo: ana@exemplo.com",
  rateLimited:
    "Você atingiu o limite de 5 envios por hora a partir desta conexão. Tente de novo mais tarde.",
  error: "Não conseguimos registrar agora. Tente de novo em alguns minutos.",
  success: "Recebemos seu aviso. Resposta da redação em até 24 h.",
  honeypotLabel: "Não preencha este campo",
  close: "Fechar",
} as const;

/** Matéria (P03), histórico (P04) e ações de leitura. */
export const ARTICLE = {
  breadcrumb: "Você está em",
  home: "Início",
  published: "Publicado em",
  updated: "Atualizado em",
  readMinutes: (n: number) => `${n} min de leitura`,
  sources: (n: number) => (n === 1 ? "1 fonte" : `${n} fontes`),
  actions: "Ações da matéria",
  aiTitle: "Resumo em poucos segundos",
  aiReviewed: (name: string) => `Resumo revisado por ${name}.`,
  aiNotReviewed: "Revisado automaticamente. Confira os detalhes no texto completo.",
  aiUseful: "Foi útil?",
  yes: "Sim",
  no: "Não",
  thanks: "Obrigado pelo retorno.",
  updateNote: "Atualização",
  correctionNote: "Correção",
  noteAt: (when: string) => `em ${when}`,
  seeChanges: "Ver o que mudou",
  sourcesTitle: "Fontes",
  sourcesIntro: "Onde o CityNews encontrou cada informação. Os links abrem no site de origem.",
  ownReporting: "Apuração própria da redação do CityNews.",
  role: { primary: "Fonte primária", secondary: "Fonte secundária", context: "Contexto" },
  confirmed: "Confirmada pela redação",
  unconfirmed: "Ainda não confirmada",
  openSource: (name: string) => `Abrir em ${name}`,
  newTab: "abre em nova aba",
  tags: "Temas",
  topicTag: (title: string) => `Assunto: ${title}`,
  ask: "Pergunte sobre esta matéria",
  askIntro: "O CityNews responde só com fontes e mostra de onde veio cada frase.",
  askQuestions: (title: string, topic?: string) => [
    topic ? `O que já se sabe sobre “${topic}”?` : `O que já se sabe sobre “${title}”?`,
    "O que ainda não foi confirmado neste caso?",
    "Quais fontes oficiais tratam deste assunto?",
  ],
  related: "Semelhantes",
  imageCredit: (credit: string) => `Crédito: ${credit}`,
  updatedWhileReading: (hour: string) => `Esta matéria foi atualizada às ${hour}`,
  reload: "Recarregar",
  share: "Compartilhar",
  shareTitle: "Compartilhar matéria",
  shareWhatsapp: "WhatsApp",
  shareEmail: "E-mail",
  copyLink: "Copiar link",
  copied: "Link copiado.",
  adjust: "Ajustar leitura",
  adjustTitle: "Ajustar leitura",
  textSize: "Tamanho do texto",
  sizes: { md: "Padrão", lg: "Grande", xl: "Maior" },
  theme: "Tema",
  themes: { light: "Claro", dark: "Escuro" },
  done: "Pronto",
  goneTitle: "Esta matéria foi retirada do ar",
  goneCorrections: "Ver correções publicadas",
  errorTitle: "Não conseguimos carregar esta matéria agora",
  errorText: "Pode ser uma instabilidade passageira. Tente de novo em alguns minutos.",
  historyTitle: "Histórico de versões",
  historyIntro:
    "Todas as versões publicadas desta matéria, da mais recente para a primeira. Não mostramos rascunhos nem comentários internos da redação.",
  historyLegend:
    "Legenda: trechos acrescentados aparecem sublinhados e com o aviso “acrescentado”; trechos removidos aparecem riscados e com o aviso “removido”.",
  added: "acrescentado",
  removed: "removido",
  version: (n: number) => `Versão ${n}`,
  versionKind: { edit: "Publicação", update: "Atualização", correction: "Correção" },
  firstVersion: "Primeira versão publicada.",
  noChanges: "Sem mudança no texto.",
  backToArticle: "Voltar para a matéria",
  historyEmpty: "Esta matéria ainda não tem versões publicadas.",
} as const;
