export { SOURCE_CATEGORY_TEXT, SOURCES_PAGE } from "./sources-list";

/** Página da fonte (P15). */
export const SOURCE_PAGE_TEXT = {
  metaTitle: (name: string) => `${name} · Fontes · CityNews Cuiabá`,
  metaDescription: (name: string, where: string) =>
    `Notícias de ${name} (${where}) acompanhadas pelo CityNews, com link para o original. Como o CityNews exibe o conteúdo desta fonte.`,
  breadcrumb: "Trilha",
  sourcesLink: "Fontes",
  intro: (categories: string, where: string) =>
    `Veículo de ${where} que cobre ${categories}. O CityNews mostra só título, data, um resumo próprio quando a fonte permite e o link para o original.`,
  openSite: "Abrir site da fonte",
  openSiteLabel: (name: string) => `Abrir site de ${name}, abre em nova aba`,
  statsLabel: "Números aproximados",
  reach: "Alcance aproximado em 30 dias",
  today: "Matérias hoje",
  updated: "Última atualização",
  filterLabel: "Filtrar por editoria",
  all: "Todas",
  itemsTitle: "Últimas desta fonte",
  itemsNotice: "Cada item abre no site da fonte, em nova aba.",
  itemsEmpty: "Nenhum item recente desta fonte",
  itemsEmptyFiltered: "Nenhum item recente nesta editoria",
  itemsEmptyText: "Quando a fonte publicar, os links aparecem aqui.",
  brokenLink: "Link quebrado?",
  brokenLinkLabel: (title: string) => `Avisar link quebrado: ${title}`,
  brokenLinkSending: "Enviando…",
  brokenLinkDone: "Obrigado. A redação confere em até 24 h.",
  aboutTitle: "Sobre esta fonte no CityNews",
  integration: "Integração",
  kinds: {
    rss: "Feed RSS",
    sitemap: "Sitemap de notícias",
    api: "API oficial",
    page: "Página pública",
    newsletter: "Newsletter",
    social: "Rede social",
    events: "Agenda de eventos",
  } as Record<string, string>,
  frequency: "Frequência",
  every: (min: number) => (min % 60 === 0 ? `A cada ${min / 60} h` : `A cada ${min} min`),
  display: "Exibição",
  displayText: {
    summary_2_sentences: "Título, data, resumo próprio do CityNews (até 2 frases) e link",
    link_only: "Só título, data e link",
  } as Record<string, string>,
  images: "Imagens",
  imagesText: {
    none: "Sem imagens da fonte",
    with_agreement: "Só com acordo registrado",
    licensed_only: "Só imagens licenciadas",
    reproduction: "Reprodução com crédito e link",
  } as Record<string, string>,
  agreement: "Acordo",
  agreementUntil: (date: string) => `Vigente até ${date}`,
  noAgreement: "Sem acordo: só link para o original",
  availability: "Disponibilidade em 30 dias",
  availabilityText: (pct: number) => `${pct}% das coletas`,
  availabilityNone: "Ainda sem histórico de coleta",
  contact: "Correção ou remoção",
  contactText: "Fale com a redação",
  contactHref: "/contato",
  notFound: "Fonte não encontrada",
  errorTitle: "Não conseguimos carregar esta fonte agora",
  errorText: "Pode ser uma instabilidade passageira. A lista de fontes continua disponível.",
  backToSources: "Ver todas as fontes",
  loading: "Carregando a fonte",
} as const;

/** Panorama de fontes (P16): camada secundária, sempre em superfície neutra e rotulada. */
export const PANORAMA_TEXT = {
  metaTitle: "Panorama de fontes · CityNews Cuiabá",
  metaDescription:
    "O que outros veículos de Cuiabá e Mato Grosso publicaram, com link para o original e comparação de coberturas.",
  title: "Panorama de fontes",
  eyebrow: "AGREGADO · OUTROS VEÍCULOS",
  intro:
    "O que outros veículos publicaram, com a origem de cada link. É uma camada secundária: a reportagem do CityNews continua na página inicial.",
  notice: "Tudo nesta página é de outros veículos e abre no site de cada um.",
  homeLink: "Ver as notícias do CityNews",
  themes: "Temas",
  allThemes: "Todos",
  compareTitle: "Comparar coberturas",
  compareIntro: (topic: string) => `Assunto mais ativo agora: ${topic}.`,
  compareSummary: (covered: number, missing: number) =>
    `${covered === 1 ? "1 veículo cobriu" : `${covered} veículos cobriram`} · ${
      missing === 1 ? "1 sem cobertura" : `${missing} sem cobertura`
    }`,
  citynews: "CityNews",
  citynewsCount: (n: number) =>
    n === 0 ? "Sem matéria própria ainda" : n === 1 ? "1 matéria" : `${n} matérias`,
  citynewsLink: "Ver cobertura do CityNews",
  itemsCount: (n: number) => (n === 1 ? "1 item" : `${n} itens`),
  covered: "Cobriu",
  first: "Primeira a publicar",
  difference: (hours: number) =>
    hours < 1 ? "Menos de 1 h depois da primeira" : `${hours} h depois da primeira`,
  noCoverage: "Sem cobertura",
  compareEmpty: "Nenhum assunto com cobertura de vários veículos agora.",
  latestTitle: "Mais recentes das suas fontes",
  order: "Ordem",
  orderRecent: "Recentes",
  /** Ordena pela popularidade da fonte, não da matéria (UX-W4-T4, item 73). */
  orderRead: "Fontes mais lidas primeiro",
  picker: "Fontes exibidas",
  pickerCount: (shown: number, total: number) => `${shown} de ${total} fontes`,
  pickerHint: "A escolha fica só neste navegador.",
  pickerAll: "Todas",
  pickerFollowed: "Só as que sigo",
  latestEmpty: "Nenhum item das fontes escolhidas",
  latestEmptyText: "Escolha mais fontes acima ou veja todas.",
  showAll: "Mostrar todas",
  errorTitle: "Não conseguimos carregar o Panorama agora",
  errorText: "Pode ser uma instabilidade passageira. As notícias do CityNews continuam no ar.",
  unconfiguredTitle: "O Panorama ainda não está disponível",
  unconfiguredText:
    "O CityNews ainda está preparando a lista de veículos acompanhados. As notícias e a agenda continuam no ar.",
  retry: "Tentar de novo",
  loading: "Carregando o Panorama",
} as const;
