import type { Role } from "@/lib/auth";

export const STUDIO_TEXT = {
  name: "Estúdio",
  nav: "Estúdio",
  signedInAs: "Conectado como",
  welcome: "Bem-vindo ao Estúdio",
  intro:
    "Redação, Control Center e Governança ficam aqui. A navegação lateral mostra só o que o seu papel permite.",
  loading: "Carregando",
  backToSite: "Ver o portal",
} as const;

export const ROLE_LABEL: Record<Role, string> = {
  admin: "Administração",
  editor_chefe: "Editor-chefe",
  editor: "Editor",
  jornalista: "Jornalista",
  revisor: "Revisor",
  operador_ia: "Operador de IA",
  analista: "Analista",
  moderador: "Moderador",
  leitura: "Leitura",
};

export const ARTICLE_STATUS_LABEL = {
  draft: "Rascunho",
  in_review: "Em revisão",
  changes_requested: "Ajustes pedidos",
  approved: "Aprovada",
  scheduled: "Agendada",
  published: "Publicada",
  updated: "Atualizada",
  archived: "Arquivada",
  unpublished: "Despublicada",
} as const;

/** Rota recomendada pelas regras (decisions.recommended). */
export const RECOMMENDED_LABEL: Record<string, string> = {
  publish: "Publicar",
  publish_notify: "Publicar e avisar",
  review: "Revisar",
  hold: "Reter",
};

export const CONFIDENCE_LABEL = { alta: "Alta", média: "Média", baixa: "Baixa" } as const;

export const QUEUE_TEXT = {
  newsroomTitle: "Newsroom",
  queueTitle: "Fila de matérias",
  kpiRegion: "Indicadores do dia",
  kpi: {
    publishedToday: "Publicadas hoje",
    auto24h: "Automáticas em 24 h",
    exceptions: "Fila de exceção",
    overdue: "Prazo vencido",
    scheduled: "Agendadas",
  },
  tabsLabel: "Abas da fila",
  tabs: {
    all: "Tudo",
    exceptions: "Fila de exceção",
    auto24h: "Publicadas automaticamente em 24 h",
    mine: "Minha fila",
    sensitive: "Temas sensíveis",
  },
  autoBanner: (n: number) =>
    n === 1
      ? "1 matéria foi publicada automaticamente nas últimas 24 h. Confira e despublique com motivo se algo estiver errado."
      : `${n} matérias foram publicadas automaticamente nas últimas 24 h. Confira e despublique com motivo se algo estiver errado.`,
  autoBannerLink: "Ver publicadas automaticamente",
  seeAll: "Ver fila completa",
  caption: "Matérias da fila",
  scrollRegion: "Tabela da fila (role para os lados no celular)",
  col: {
    select: "Selecionar",
    title: "Matéria",
    status: "Estado",
    recommended: "Recomendação da IA",
    assignee: "Responsável",
    due: "Prazo",
    actions: "Ações",
  },
  selectRow: (title: string) => `Selecionar "${title}"`,
  noAssignee: "Sem responsável",
  noRecommendation: "Sem recomendação",
  noDue: "Sem prazo",
  overdue: "Vencido",
  sensitive: "Tema sensível",
  aiFallback: "Sem IA",
  pipeline: "Pipeline",
  auto: "Automática",
  open: "Abrir",
  review: "Revisar",
  unpublish: "Despublicar",
  unpublishTitle: "Despublicar matéria automática",
  unpublishIntro:
    "A matéria sai do portal na hora. O motivo fica registrado na decisão humana e na auditoria.",
  reason: "Motivo",
  reasonHint: "Ex.: data incorreta no alerta",
  reasonRequired: "Escreva o motivo da despublicação",
  confirm: "Confirmar",
  cancel: "Cancelar",
  unpublished: (title: string) => `Despublicada: ${title}`,
  notAuto: "Só matérias publicadas automaticamente podem ser despublicadas por aqui.",
  notPublished: "A matéria não está publicada.",
  notDraft: "Só rascunhos ou matérias com ajuste pedido voltam para revisão.",
  forbidden: "Seu papel não permite esta ação nesta matéria.",
  genericError: "Não foi possível concluir. Tente de novo.",
  bulkLabel: "Ações em lote",
  bulkSelected: (n: number) =>
    n === 0 ? "Nenhuma selecionada" : n === 1 ? "1 selecionada" : `${n} selecionadas`,
  assignTo: "Atribuir a",
  assignButton: "Atribuir selecionadas",
  assigned: (n: number) => (n === 1 ? "1 matéria atribuída" : `${n} matérias atribuídas`),
  requestReview: "Pedir revisão",
  reviewRequested: (n: number) =>
    n === 1 ? "1 matéria enviada para revisão" : `${n} matérias enviadas para revisão`,
  unpublishSelected: "Despublicar automáticas",
  unpublishedMany: (n: number) =>
    n === 1 ? "1 matéria despublicada" : `${n} matérias despublicadas`,
  failedSome: (n: number) => (n === 1 ? "1 não foi alterada" : `${n} não foram alteradas`),
  filters: "Filtros",
  filterApply: "Filtrar",
  filterClear: "Limpar filtros",
  filter: {
    status: "Estado",
    section: "Editoria",
    origin: "Origem",
    confidence: "Confiança",
    assignee: "Responsável",
    due: "Prazo",
    any: "Todos",
    me: "Eu",
    none: "Sem responsável",
    original: "Original da redação",
    pipeline: "Pipeline",
    auto: "Publicada automaticamente",
    overdue: "Vencido",
    today: "Até hoje",
  },
  emptyTitle: "Nada na fila",
  empty: {
    all: "Nenhuma matéria com esses filtros.",
    exceptions: "O pipeline não mandou nenhum item para revisão humana.",
    auto24h: "Nenhuma matéria foi publicada automaticamente nas últimas 24 h.",
    mine: "Nenhuma matéria atribuída a você ou em andamento com a sua autoria.",
    sensitive: "Nenhuma matéria de tema sensível em aberto.",
  },
  errorTitle: "A fila não carregou",
  errorBody: "O banco não respondeu. Tente de novo em instantes; nada foi alterado.",
  retry: "Tentar de novo",
  loading: "Carregando a fila",
} as const;

export const CHECKLIST_TEXT = {
  title: "Checklist de publicação",
  complete: "Checklist completo",
  pending: (n: number) => (n === 1 ? "1 item pendente" : `${n} itens pendentes`),
  label: {
    titleDek: "Título e linha fina",
    taxonomy: "Editoria, tags e local",
    primary: "Fonte primária confirmada",
    primaryOptional: "Fonte primária (não exigida nesta editoria)",
    images: "Crédito e texto alternativo das imagens",
    seo: "SEO: título e descrição",
    suggestions: "Sugestões de IA resolvidas",
  },
  reason: {
    titleDek: "Falta título ou linha fina",
    taxonomy: "Falta editoria, tag ou local",
    primary: "Falta fonte primária confirmada",
    credit: "Falta crédito da imagem",
    alt: "Falta texto alternativo da imagem",
    seo: "Falta título ou descrição de SEO",
    seoTitleLong: (max: number) => `Título de SEO passa de ${max} caracteres`,
    seoDescriptionLong: (max: number) => `Descrição de SEO passa de ${max} caracteres`,
    suggestions: (n: number) =>
      n === 1 ? "Há 1 sugestão de IA sem decisão" : `Há ${n} sugestões de IA sem decisão`,
  },
  ok: "ok",
  missing: "pendente",
} as const;

export const EDITOR_TEXT = {
  title: "Editor de matéria",
  conflict:
    "Outra pessoa salvou esta matéria depois que você abriu. Nada foi sobrescrito: compare as mudanças abaixo e recarregue para continuar.",
  conflictTitle: "Conflito de edição",
  conflictReload: "Recarregar a versão atual",
  conflictSaved: "Versão salva por outra pessoa",
  conflictMine: "O que você tentou salvar",
  publishedNeedsMode:
    "Matéria publicada: use o modo Atualização ou Correção para mudar o texto público.",
  suggestionDecided: "Esta sugestão já foi decidida.",
  saved: (v: number) => `Rascunho salvo · versão ${v}`,
  save: "Salvar rascunho",
  saving: "Salvando…",
  fields: {
    title: "Título",
    dek: "Linha fina",
    body: "Texto",
    section: "Editoria",
    tags: "Tags",
    tagsHint: "Separe por vírgula. Ex.: ônibus, transporte",
    neighborhoods: "Local (bairros)",
    neighborhoodsHint: "Bairros citados, separados por vírgula. Ex.: cpa, centro-norte",
    seoTitle: "Título de SEO",
    seoDescription: "Descrição de SEO",
    topic: "Assunto",
    noTopic: "Sem assunto",
  },
  counter: (n: number, max: number) => `${n} de ${max} caracteres`,
  originAi: (name: string) => `Sugerido pela IA · aceito por ${name}`,
  originHuman: (name: string) => `Editado por ${name}`,
  originPipeline: "Gerado pela IA (pipeline) · ainda sem edição humana",
  suggestions: "Sugestões da IA",
  suggestionsIntro:
    "Nada entra na matéria sem o seu clique. Ao aplicar, o campo fica marcado com a origem da IA e o seu nome.",
  noSuggestions: "Nenhuma sugestão aberta.",
  apply: {
    title: "Aplicar título sugerido",
    dek: "Aplicar linha fina sugerida",
    seo_title: "Aplicar título de SEO sugerido",
    seo_description: "Aplicar descrição de SEO sugerida",
    body: "Inserir parágrafo sugerido",
  },
  discard: "Descartar",
  suggestionField: {
    title: "Título",
    dek: "Linha fina",
    seo_title: "Título de SEO",
    seo_description: "Descrição de SEO",
    body: "Parágrafo",
  },
  agent: (agent: string, v: number | null) =>
    v === null ? `Agente ${agent}` : `Agente ${agent} · prompt v${v}`,
  applied: "Sugestão aplicada",
  discarded: "Sugestão descartada",
  sources: "Fontes",
  sourcesIntro: "Itens coletados que sustentam a matéria, com papel e confirmação.",
  noSources: "Nenhuma fonte vinculada.",
  sourceRole: { primary: "Primária", secondary: "Secundária", context: "Contexto" },
  sourceConfirmed: "Confirmada",
  sourceUnconfirmed: "A confirmar",
  confirmSource: "Confirmar",
  unconfirmSource: "Desfazer confirmação",
  removeSource: "Remover",
  addSource: "Adicionar fonte",
  addSourceLabel: "Item coletado",
  addSourceHint: "Itens do mesmo assunto ou da mesma editoria",
  roleLabel: "Papel",
  sourcesSaved: "Fontes atualizadas",
  confidenceLive: "Confiança calculada",
  conflictAlert: "As fontes divergem sobre um fato central. Revise antes de publicar.",
  labels: "Rótulos gerados",
  history: "Versões",
  openHistory: "Comparar versões",
  bodyToolbar: "Formatação do texto",
  bold: "Negrito",
  italic: "Itálico",
  heading: "Intertítulo",
  paragraph: "Parágrafo",
  aiMarkLegend: "Trecho sugerido pela IA",
  humanMarkLegend: "Trecho editado por pessoa",
  statusLine: (status: string, version: number) => `${status} · versão ${version}`,
  readonly: "Seu papel não permite editar esta matéria.",
  notFoundTitle: "Matéria não encontrada",
  notFound: "A matéria não existe ou seu papel não permite abri-la.",
  back: "Voltar para a fila",
} as const;

export const REVIEW_TEXT = {
  title: "Revisão de item autônomo",
  labels: "Rótulos",
  state: "Estado",
  reason: "Por que está na fila",
  fields: "Campos modificados",
  fieldsIntro: "Primeira versão da IA × texto atual. Acréscimos sublinhados, remoções riscadas.",
  noChanges: "Nenhum campo mudou desde a versão da IA.",
  noAiVersion: "Sem versão da IA para comparar.",
  fieldAi: "IA",
  fieldHuman: "Humano",
  justification: "Justificativa da IA",
  stepCol: "Etapa",
  justificationTable: "Tabela de decisões (role para os lados no celular)",
  step: {
    write: "Redação",
    summarize: "Redação",
    rules: "Regras",
    publish: "Publicação",
    review: "Revisão humana",
    verify: "Verificação",
  } as Record<string, string>,
  agent: "Agente",
  promptVersion: "Versão do prompt",
  rulesVersion: "Versão das regras",
  at: "Horário",
  noDecisions: "Nenhuma decisão registrada.",
  recommendedVsHuman: "Decisão recomendada × decisão humana",
  recommended: "Recomendada pela IA",
  human: "Decisão humana",
  pendingHuman: "Aguardando decisão",
  humanDecision: {
    approve: "Aprovada",
    reject: "Rejeitada",
    request_changes: "Ajuste pedido",
    reprocess: "Reprocessar",
    unpublish: "Despublicada",
  } as Record<string, string>,
  image: "Imagem escolhida",
  noImage: "Nenhuma imagem escolhida.",
  alerts: "Alertas",
  aiFallbackAlert: "Rascunho montado sem IA: confira fontes e texto com atenção.",
  sensitiveAlert: "Tema sensível: nunca publica sozinho.",
  history: "Histórico",
  actions: "Decisão",
  reject: "Rejeitar",
  requestChanges: "Pedir ajuste",
  reprocess: "Reprocessar",
  approve: "Aprovar e publicar",
  approveDisabled: (why: string) => `Aprovar indisponível: ${why}`,
  edit: "Abrir no editor",
  reasonLabel: "Motivo",
  noteLabel: "Orientação para a redação",
  reasonRequired: "Escreva o motivo",
  confirm: "Confirmar",
  cancel: "Cancelar",
  rejected: "Item rejeitado e retirado da fila",
  changesRequested: "Ajuste pedido à redação",
  reprocessed: "Enviado de novo para o pipeline",
  approved: "Aprovada e publicada",
  notReviewable: "Este item já saiu da fila de revisão.",
  cannotReprocess: "Só matéria do pipeline sem edição humana pode ser reprocessada.",
  sourcesInvalid: "Uma das fontes não existe mais.",
  sourcesTitle: "Origem e fontes relacionadas",
  forbidden: "Seu papel não permite esta ação nesta matéria.",
  genericError: "Não foi possível concluir. Tente de novo.",
} as const;

export const VERSIONS_TEXT = {
  title: "Comparação de versões",
  from: "Versão anterior",
  to: "Versão nova",
  compare: "Comparar",
  legendAdded: "Acrescentado",
  legendRemoved: "Removido",
  legend: "Legenda",
  unchanged: "Sem mudança neste campo.",
  noChanges: "As duas versões têm o mesmo título, linha fina e texto.",
  list: "Todas as versões",
  kind: { edit: "Edição", update: "Atualização", correction: "Correção" } as Record<string, string>,
  origin: { ai: "IA", human: "Humano" },
  option: (n: number, kind: string, date: string) => `v${n} · ${kind} · ${date}`,
  publicNote: "Nota pública",
  single: "Esta matéria tem uma versão só. A comparação aparece a partir da segunda.",
  back: "Voltar ao editor",
  notFound: "Matéria não encontrada",
} as const;

export const PUBLISH_TEXT = {
  open: "Publicar",
  title: "Publicação e agendamento",
  checklist: "Checklist",
  checklistOk: "Checklist completo",
  labels: "Rótulos finais",
  when: "Quando",
  now: "Publicar agora",
  schedule: "Agendar",
  at: "Data e hora (fuso de Cuiabá)",
  atHint: "Horário de Cuiabá. Ex.: 29/09 às 7h",
  destinations: "Destinos",
  destination: {
    home: "Home",
    section: "Editoria",
    topic: "Página do assunto",
    newsletter: "Newsletter",
  },
  noTopic: "sem assunto vinculado",
  push: "Push de urgente",
  pushNote: "Push exige 2 aprovações no Control Center. Publicar aqui não dispara push.",
  headline: (title: string) => `A manchete atual da home é "${title}". Esta matéria entra no topo.`,
  confirm: "Confirmar publicação",
  confirmSchedule: "Confirmar agendamento",
  cancel: "Cancelar",
  published: "Matéria publicada",
  scheduled: (when: string) => `Matéria agendada para ${when}`,
  pastDate: "Escolha um horário futuro",
  invalidDate: "Data ou hora inválida",
  tooFar: "Agende para no máximo 90 dias",
  blocked: (why: string) => `Publicação indisponível: ${why}`,
  alreadyPublic: "A matéria já está publicada. Use Atualização ou Correção.",
} as const;
