import type { Role } from "@/lib/auth";
import type { ConfidenceLevel } from "@/lib/confidence";

/** Nível de confiança: só no Estúdio (spec 2026-10-03 R13). */
export const CONFIDENCE_TEXT: Record<ConfidenceLevel, string> = {
  alta: "Confiança alta",
  média: "Confiança média",
  baixa: "Confiança baixa",
};

export const STUDIO_TEXT = {
  name: "Estúdio",
  nav: "Estúdio",
  signedInAs: "Conectado como",
  welcome: "Bem-vindo ao Estúdio",
  intro:
    "Redação, Control Center e Governança ficam aqui. A navegação lateral mostra só o que o seu papel permite.",
  loading: "Carregando",
  backToSite: "Ver o portal",
  errorTitle: "Não foi possível carregar esta tela do Estúdio",
  errorText:
    "O banco não respondeu agora. Nada do que você salvou antes se perdeu. Tente de novo em instantes.",
  errorCode: (digest: string) => `Código do erro: ${digest}`,
  retry: "Tentar de novo",
  backToNewsroom: "Voltar para a redação",
  openMenu: "Abrir menu",
  closeMenu: "Fechar menu",
  menuLabel: "Menu",
  menuTitle: "Menu do Estúdio",
  menuSearch: "Buscar no menu",
  menuEmpty: (q: string) => `Nenhuma tela com “${q}”.`,
} as const;

export const ROLE_LABEL: Record<Role, string> = {
  admin: "Administração",
  editor_chefe: "Editor-chefe",
  editor: "Editor",
  jornalista: "Jornalista",
  revisor: "Revisor",
  operador_ia: "Operador de IA",
  analista: "Analista",
  moderador: "Moderador",
  leitura: "Leitura",
};

export const ARTICLE_STATUS_LABEL = {
  draft: "Rascunho",
  in_review: "Em revisão",
  changes_requested: "Ajustes pedidos",
  approved: "Aprovada",
  scheduled: "Agendada",
  published: "Publicada",
  updated: "Atualizada",
  archived: "Arquivada",
  unpublished: "Despublicada",
} as const;

/** Rota recomendada pelas regras (decisions.recommended). */
export const RECOMMENDED_LABEL: Record<string, string> = {
  publish: "Publicar",
  publish_notify: "Publicar e avisar",
  review: "Revisar",
  hold: "Reter",
};

export const CONFIDENCE_LABEL = { alta: "Alta", média: "Média", baixa: "Baixa" } as const;

export const QUEUE_TEXT = {
  newsroomTitle: "Newsroom",
  queueTitle: "Fila de matérias",
  kpiRegion: "Indicadores do dia",
  kpi: {
    publishedToday: "Publicadas hoje",
    auto24h: "Automáticas em 24 h",
    exceptions: "Fila de exceção",
    overdue: "Prazo vencido",
    scheduled: "Agendadas",
  },
  tabsLabel: "Abas da fila",
  tabs: {
    all: "Tudo",
    exceptions: "Fila de exceção",
    auto24h: "Publicadas automaticamente em 24 h",
    mine: "Minha fila",
    sensitive: "Temas sensíveis",
  },
  autoBanner: (n: number) =>
    n === 1
      ? "1 matéria foi publicada automaticamente nas últimas 24 h. Confira e despublique com motivo se algo estiver errado."
      : `${n} matérias foram publicadas automaticamente nas últimas 24 h. Confira e despublique com motivo se algo estiver errado.`,
  autoBannerLink: "Ver publicadas automaticamente",
  seeAll: "Ver fila completa",
  loadMore: "Carregar mais",
  caption: "Matérias da fila",
  scrollRegion: "Tabela da fila (role para os lados no celular)",
  col: {
    select: "Selecionar",
    title: "Matéria",
    status: "Estado",
    recommended: "Recomendação da IA",
    assignee: "Responsável",
    due: "Prazo",
    actions: "Ações",
  },
  selectRow: (title: string) => `Selecionar "${title}"`,
  noAssignee: "Sem responsável",
  noRecommendation: "Sem recomendação",
  noDue: "Sem prazo",
  overdue: "Atrasada",
  sensitive: "Tema sensível",
  aiFallback: "Sem IA",
  pipeline: "Pipeline",
  auto: "Automática",
  open: "Abrir",
  review: "Revisar",
  unpublish: "Despublicar",
  unpublishTitle: "Despublicar matéria automática",
  unpublishIntro:
    "A matéria sai do portal na hora. O motivo fica registrado na decisão humana e na auditoria.",
  reason: "Motivo",
  reasonHint: "Ex.: data incorreta no alerta",
  reasonRequired: "Escreva o motivo da despublicação",
  confirm: "Confirmar",
  cancel: "Cancelar",
  unpublished: (title: string) => `Despublicada: ${title}`,
  notAuto: "Só matérias publicadas automaticamente podem ser despublicadas por aqui.",
  notPublished: "A matéria não está publicada.",
  notDraft: "Só rascunhos ou matérias com ajuste pedido voltam para revisão.",
  assigneeInvalid: "Escolha alguém da redação (edição, reportagem ou revisão).",
  forbidden: "Seu papel não permite esta ação nesta matéria.",
  genericError: "Não foi possível concluir. Tente de novo.",
  bulkLabel: "Ações em lote",
  bulkSelected: (n: number) =>
    n === 0 ? "Nenhuma selecionada" : n === 1 ? "1 selecionada" : `${n} selecionadas`,
  assignTo: "Atribuir a",
  assignButton: "Atribuir selecionadas",
  assigned: (n: number) => (n === 1 ? "1 matéria atribuída" : `${n} matérias atribuídas`),
  requestReview: "Pedir revisão",
  reviewRequested: (n: number) =>
    n === 1 ? "1 matéria enviada para revisão" : `${n} matérias enviadas para revisão`,
  unpublishSelected: "Despublicar automáticas",
  unpublishedMany: (n: number) =>
    n === 1 ? "1 matéria despublicada" : `${n} matérias despublicadas`,
  failedSome: (n: number) => (n === 1 ? "1 não foi alterada" : `${n} não foram alteradas`),
  filters: "Filtros",
  filterApply: "Filtrar",
  filterClear: "Limpar filtros",
  filter: {
    status: "Estado",
    section: "Editoria",
    origin: "Origem",
    confidence: "Confiança",
    assignee: "Responsável",
    due: "Prazo",
    any: "Todos",
    me: "Eu",
    none: "Sem responsável",
    original: "Original da redação",
    pipeline: "Pipeline",
    auto: "Publicada automaticamente",
    overdue: "Vencido",
    today: "Até hoje",
  },
  emptyTitle: "Nada na fila",
  empty: {
    all: "Nenhuma matéria com esses filtros.",
    exceptions: "O pipeline não mandou nenhum item para revisão humana.",
    auto24h: "Nenhuma matéria foi publicada automaticamente nas últimas 24 h.",
    mine: "Nenhuma matéria atribuída a você ou em andamento com a sua autoria.",
    sensitive: "Nenhuma matéria de tema sensível em aberto.",
  },
  errorTitle: "A fila não carregou",
  errorBody: "O banco não respondeu. Tente de novo em instantes; nada foi alterado.",
  retry: "Tentar de novo",
  loading: "Carregando a fila",
} as const;

export const IMAGE_TEXT = {
  title: "Imagem da matéria",
  none: "A matéria ainda não tem imagem.",
  alt: "Texto alternativo",
  altHint: "Descreva o que a imagem mostra para quem usa leitor de tela. Até 250 caracteres.",
  decorative: "Imagem decorativa (não acrescenta informação; texto alternativo fica vazio)",
  caption: "Legenda (opcional)",
  captionHint: "Aparece junto da imagem. Até 300 caracteres.",
  save: "Salvar texto da imagem",
  saved: "Texto da imagem salvo",
  count: (n: number, max: number) => `${n} de ${max} caracteres`,
  altRequired: "Escreva o texto alternativo ou marque a imagem como decorativa",
  altTooLong: (max: number) => `O texto alternativo passa de ${max} caracteres`,
  captionTooLong: (max: number) => `A legenda passa de ${max} caracteres`,
  missing: "Sem texto alternativo",
  decorativeShort: "Decorativa",
  forArticle: (title: string) => `Texto da imagem em "${title}"`,
} as const;

export const CHECKLIST_TEXT = {
  title: "Checklist de publicação",
  complete: "Checklist completo",
  pending: (n: number) => (n === 1 ? "1 item pendente" : `${n} itens pendentes`),
  label: {
    titleDek: "Título e linha fina",
    taxonomy: "Editoria, tags e local",
    primary: "Fonte primária confirmada",
    primaryOptional: "Fonte primária (não exigida nesta editoria)",
    images: "Crédito e texto alternativo das imagens",
    seo: "SEO: título e descrição",
    suggestions: "Sugestões de IA resolvidas",
    aiFallback: "Texto reescrito pela redação (rascunho sem IA)",
  },
  reason: {
    titleDek: "Falta título ou linha fina",
    taxonomy: "Falta editoria, tag ou local",
    primary: "Falta fonte primária confirmada",
    credit: "Falta crédito da imagem",
    alt: "Falta texto alternativo da imagem",
    seo: "Falta título ou descrição de SEO",
    seoTitleLong: (max: number) => `Título de SEO passa de ${max} caracteres`,
    seoDescriptionLong: (max: number) => `Descrição de SEO passa de ${max} caracteres`,
    suggestions: (n: number) =>
      n === 1 ? "Há 1 sugestão de IA sem decisão" : `Há ${n} sugestões de IA sem decisão`,
    aiFallback: "Rascunho sem IA: reescreva o texto das fontes antes de publicar",
  },
  ok: "ok",
  missing: "pendente",
} as const;

export const EDITOR_TEXT = {
  title: "Editor de matéria",
  conflict:
    "Outra pessoa salvou esta matéria depois que você abriu. Nada foi sobrescrito: compare as mudanças abaixo e recarregue para continuar.",
  conflictTitle: "Conflito de edição",
  conflictReload: "Recarregar a versão atual",
  conflictSaved: "Versão salva por outra pessoa",
  conflictMine: "O que você tentou salvar",
  draftKept: "Guardamos o seu texto neste aparelho.",
  draftKeptHint: "Confira a versão atual e, se quiser, traga o seu texto de volta para continuar.",
  restoreDraft: "Restaurar meu texto",
  discardDraft: "Descartar meu texto",
  publishedNeedsMode:
    "Matéria publicada: use o modo Atualização ou Correção para mudar o texto público.",
  suggestionDecided: "Esta sugestão já foi decidida.",
  formerStaff: "Ex-integrante da redação",
  aiMarkForged: "Trecho marcado como sugestão de IA só entra pelo botão Aceitar.",
  unscheduled: (v: number) =>
    `Rascunho salvo · versão ${v}. O agendamento foi cancelado: revise e agende de novo.`,
  saved: (v: number) => `Rascunho salvo · versão ${v}`,
  save: "Salvar rascunho",
  saving: "Salvando…",
  fields: {
    title: "Título",
    dek: "Linha fina",
    body: "Texto",
    section: "Editoria",
    tags: "Tags",
    tagsHint: "Separe por vírgula. Ex.: ônibus, transporte",
    neighborhoods: "Local (bairros)",
    neighborhoodsHint: "Bairros citados, separados por vírgula. Ex.: cpa, centro-norte",
    seoTitle: "Título de SEO",
    seoDescription: "Descrição de SEO",
    topic: "Assunto",
    noTopic: "Sem assunto",
  },
  counter: (n: number, max: number) => `${n} de ${max} caracteres`,
  originAi: (name: string) => `Sugerido pela IA · aceito por ${name}`,
  originHuman: (name: string) => `Editado por ${name}`,
  originPipeline: "Gerado pela IA (pipeline) · ainda sem edição humana",
  suggestions: "Sugestões da IA",
  suggestionsIntro:
    "Nada entra na matéria sem o seu clique. Ao aplicar, o campo fica marcado com a origem da IA e o seu nome.",
  noSuggestions: "Nenhuma sugestão aberta.",
  apply: {
    title: "Aplicar título sugerido",
    dek: "Aplicar linha fina sugerida",
    seo_title: "Aplicar título de SEO sugerido",
    seo_description: "Aplicar descrição de SEO sugerida",
    body: "Inserir parágrafo sugerido",
  },
  discard: "Descartar",
  suggestionField: {
    title: "Título",
    dek: "Linha fina",
    seo_title: "Título de SEO",
    seo_description: "Descrição de SEO",
    body: "Parágrafo",
  },
  agent: (agent: string, v: number | null) =>
    v === null ? `Agente ${agent}` : `Agente ${agent} · prompt v${v}`,
  applied: "Sugestão aplicada",
  discarded: "Sugestão descartada",
  sources: "Fontes",
  sourcesIntro: "Itens coletados que sustentam a matéria, com papel e confirmação.",
  noSources: "Nenhuma fonte vinculada.",
  sourceRole: { primary: "Primária", secondary: "Secundária", context: "Contexto" },
  sourceConfirmed: "Confirmada",
  sourceUnconfirmed: "A confirmar",
  confirmSource: "Confirmar",
  unconfirmSource: "Desfazer confirmação",
  removeSource: "Remover",
  addSource: "Adicionar fonte",
  addSourceLabel: "Item coletado",
  addSourceHint: "Itens do mesmo assunto ou da mesma editoria",
  roleLabel: "Papel",
  sourcesSaved: "Fontes atualizadas",
  confidenceLive: "Confiança calculada",
  conflictAlert: "As fontes divergem sobre um fato central. Revise antes de publicar.",
  labels: "Rótulos gerados",
  history: "Versões",
  openHistory: "Comparar versões",
  bodyToolbar: "Formatação do texto",
  bold: "Negrito",
  italic: "Itálico",
  heading: "Intertítulo",
  paragraph: "Parágrafo",
  aiMarkLegend: "Trecho sugerido pela IA",
  humanMarkLegend: "Trecho editado por pessoa",
  statusLine: (status: string, version: number) => `${status} · versão ${version}`,
  readonly: "Seu papel não permite editar esta matéria.",
  notFoundTitle: "Matéria não encontrada",
  notFound: "A matéria não existe ou seu papel não permite abri-la.",
  back: "Voltar para a fila",
} as const;

export const REVIEW_TEXT = {
  title: "Revisão de item autônomo",
  labels: "Rótulos",
  state: "Estado",
  reason: "Por que está na fila",
  fields: "Campos modificados",
  fieldsIntro: "Primeira versão da IA × texto atual. Acréscimos sublinhados, remoções riscadas.",
  noChanges: "Nenhum campo mudou desde a versão da IA.",
  noAiVersion: "Sem versão da IA para comparar.",
  fieldAi: "IA",
  fieldHuman: "Humano",
  justification: "Justificativa da IA",
  stepCol: "Etapa",
  justificationTable: "Tabela de decisões (role para os lados no celular)",
  step: {
    write: "Redação",
    summarize: "Redação",
    rules: "Regras",
    publish: "Publicação",
    review: "Revisão humana",
    verify: "Verificação",
  } as Record<string, string>,
  agent: "Agente",
  promptVersion: "Versão do prompt",
  rulesVersion: "Versão das regras",
  at: "Horário",
  noDecisions: "Nenhuma decisão registrada.",
  recommendedVsHuman: "Decisão recomendada × decisão humana",
  recommended: "Recomendada pela IA",
  human: "Decisão humana",
  pendingHuman: "Aguardando decisão",
  humanDecision: {
    approve: "Aprovada",
    reject: "Rejeitada",
    request_changes: "Ajuste pedido",
    reprocess: "Reprocessar",
    unpublish: "Despublicada",
  } as Record<string, string>,
  image: "Imagem escolhida",
  noImage: "Nenhuma imagem escolhida.",
  alerts: "Alertas",
  aiFallbackAlert: "Rascunho montado sem IA: confira fontes e texto com atenção.",
  sensitiveAlert: "Tema sensível: confira a fonte citada e o tom antes de decidir.",
  history: "Histórico",
  actions: "Decisão",
  reject: "Rejeitar",
  requestChanges: "Pedir ajuste",
  reprocess: "Reprocessar",
  approve: "Aprovar e publicar",
  approveDisabled: (why: string) => `Aprovar indisponível: ${why}`,
  edit: "Abrir no editor",
  reasonLabel: "Motivo",
  noteLabel: "Orientação para a redação",
  reasonRequired: "Escreva o motivo",
  confirm: "Confirmar",
  cancel: "Cancelar",
  rejected: "Item rejeitado e retirado da fila",
  changesRequested: "Ajuste pedido à redação",
  reprocessed: "Enviado de novo para o pipeline",
  approved: "Aprovada e publicada",
  notReviewable: "Este item já saiu da fila de revisão.",
  cannotReprocess: "Só matéria do pipeline sem edição humana pode ser reprocessada.",
  sourcesInvalid: "Uma das fontes não existe mais.",
  reprocessPublic:
    "Matéria publicada ou agendada não volta ao pipeline. Use Despublicar ou Atualização.",
  sourcesPublic: "Fontes de matéria publicada mudam só pelo modo Atualização.",
  sourcesTitle: "Origem e fontes relacionadas",
  forbidden: "Seu papel não permite esta ação nesta matéria.",
  genericError: "Não foi possível concluir. Tente de novo.",
} as const;

export const VERSIONS_TEXT = {
  title: "Comparação de versões",
  from: "Versão anterior",
  to: "Versão nova",
  compare: "Comparar",
  legendAdded: "Acrescentado",
  legendRemoved: "Removido",
  legend: "Legenda",
  unchanged: "Sem mudança neste campo.",
  noChanges: "As duas versões têm o mesmo título, linha fina e texto.",
  list: "Todas as versões",
  kind: { edit: "Edição", update: "Atualização", correction: "Correção" } as Record<string, string>,
  origin: { ai: "IA", human: "Humano" },
  option: (n: number, kind: string, date: string) => `v${n} · ${kind} · ${date}`,
  publicNote: "Nota pública",
  single: "Esta matéria tem uma versão só. A comparação aparece a partir da segunda.",
  back: "Voltar ao editor",
  notFound: "Matéria não encontrada",
} as const;

export const PUBLISH_TEXT = {
  open: "Publicar",
  title: "Publicação e agendamento",
  checklist: "Checklist",
  checklistOk: "Checklist completo",
  labels: "Rótulos finais",
  when: "Quando",
  now: "Publicar agora",
  schedule: "Agendar",
  at: "Data e hora (fuso de Cuiabá)",
  atHint: "Horário de Cuiabá. Ex.: 29/09 às 7h",
  destinations: "Destinos",
  destination: {
    home: "Home",
    section: "Editoria",
    topic: "Página do assunto",
    newsletter: "Newsletter",
  },
  noTopic: "sem assunto vinculado",
  push: "Push urgente",
  pushNote:
    "Cria e aprova o aviso urgente em Notificações na mesma ação; fica registrado no histórico.",
  pushUnavailable: "Push urgente é só para admin ou editor-chefe.",
  pushJustification: "Justificativa do push",
  pushJustificationHint: "Por que este aviso é urgente (até 300 caracteres).",
  pushJustificationRequired: "Informe a justificativa do push urgente.",
  pushRequested: "Pedido de push criado. Aguardando aprovação na fila de notificações.",
  pushApproved: "Push urgente aprovado e na fila de envio. Fica registrado no histórico.",
  pushQueueLink: "Ver fila de notificações",
  pushFailed: (why: string) => `Matéria publicada, mas o pedido de push não foi criado: ${why}`,
  headline: (title: string) => `A manchete atual da home é "${title}". Esta matéria entra no topo.`,
  confirm: "Confirmar publicação",
  confirmSchedule: "Confirmar agendamento",
  saveAndPublish: "Salvar e publicar",
  saveAndSchedule: "Salvar e agendar",
  unsaved: "Há alterações não salvas no editor. Elas são salvas antes de publicar.",
  saveFailed:
    "Não foi possível salvar as alterações. Nada foi publicado: confira o aviso no editor.",
  cancel: "Cancelar",
  published: "Matéria publicada",
  scheduled: (when: string) => `Matéria agendada para ${when}`,
  pastDate: "Escolha um horário futuro",
  invalidDate: "Data ou hora inválida",
  tooFar: "Agende para no máximo 90 dias",
  blocked: (why: string) => `Publicação indisponível: ${why}`,
  alreadyPublic: "A matéria já está publicada. Use Atualização ou Correção.",
  conflict:
    "A matéria mudou depois que você abriu. Nada foi publicado: recarregue e revise a versão atual.",
  checklistChanged: "O checklist mudou. Recarregue a matéria e confira os itens pendentes.",
} as const;

export const CORRECTIONS_TEXT = {
  title: "Correções e direito de resposta",
  intro: "Pedidos de correção e de direito de resposta, com prazo de 24 h.",
  caption: "Fila de correções",
  reportMismatch: "A denúncia vinculada não é desta matéria.",
  col: {
    article: "Matéria",
    kind: "Tipo",
    requestedBy: "Solicitante",
    due: "Prazo",
    status: "Estado",
  },
  kind: { correction: "Correção", right_of_reply: "Direito de resposta" } as Record<string, string>,
  status: { open: "Aberta", published: "Publicada" } as Record<string, string>,
  overdue: "Vencido",
  open: "Tratar",
  view: "Ver",
  tabs: { open: "Abertas", published: "Publicadas" },
  tabsLabel: "Estado das correções",
  empty: {
    open: "Nenhum pedido de correção aberto.",
    published: "Nenhuma correção publicada ainda.",
  },
  emptyTitle: "Nada por aqui",
  screenTitle: "Correção",
  request: "Pedido",
  requestedBy: "Solicitante",
  due: "Prazo",
  report: "Mensagem do leitor",
  fields: "Campos corrigidos",
  fieldsHint: "Edite só o que está errado. O diff aparece no histórico público da matéria.",
  publicNote: "Nota pública",
  publicNoteHint:
    "Aparece na matéria e em /correcoes. Ex.: A feira abre às 6h, não às 5h, como informado antes.",
  notify: "Avisar quem salvou a matéria",
  notifyHint: "Leitores com conta que salvaram recebem a nota.",
  submit: "Publicar correção",
  published: (n: number) =>
    n === 0
      ? "Correção publicada"
      : n === 1
        ? "Correção publicada · 1 pessoa avisada"
        : `Correção publicada · ${n} pessoas avisadas`,
  noteRequired: "Escreva a nota pública da correção",
  updateNoteRequired: "Escreva a nota pública da atualização",
  alreadyPublished: "Esta correção já foi publicada.",
  notPublic: "Só matéria publicada recebe correção ou atualização.",
  conflict:
    "A matéria mudou depois que você abriu a correção. Nada foi publicado: recarregue e confira.",
  publishedAt: "Publicada em",
  notified: (n: number) => (n === 1 ? "1 pessoa avisada" : `${n} pessoas avisadas`),
  openFromEditor: "Abrir correção",
  updateMode: "Atualização",
  updateModeIntro:
    "Matéria publicada: mudanças entram como Atualização (fato novo, com nota pública) ou Correção (erro, com nota pública e aviso a quem salvou).",
  updateNote: "Nota pública da atualização",
  updateNoteHint: "Ex.: A prefeitura informou o novo horário às 15h.",
  updateSubmit: "Publicar atualização",
  updated: (v: number) => `Atualização publicada · versão ${v}`,
  notFound: "Pedido de correção não encontrado",
  back: "Voltar para correções",
} as const;

export const CALENDAR_TEXT = {
  title: "Calendário editorial",
  intro: "Agendadas, prazos e publicadas por dia, no fuso de Cuiabá.",
  prev: "7 dias antes",
  next: "Próximos 7 dias",
  today: "A partir de hoje",
  todayLabel: "Hoje",
  weekOf: (from: string, to: string) => `${from} a ${to}`,
  kind: { scheduled: "Agendada", due: "Prazo", published: "Publicada" },
  empty: "Nada neste dia.",
  emptyWeek: "Nenhuma matéria agendada, com prazo ou publicada nesta semana.",
  nav: "Semanas",
} as const;

export const MEDIA_TEXT = {
  title: "Biblioteca de mídia",
  intro: "Imagens do acervo com origem, crédito, licença e estado de aprovação.",
  tabsLabel: "Estado das imagens",
  tabs: { pending: "Pendentes", approved: "Aprovadas", blocked: "Bloqueadas" },
  licensesLink: "Direitos e licenças",
  empty: {
    pending: "Nenhuma imagem esperando aprovação.",
    approved: "Nenhuma imagem aprovada ainda.",
    blocked: "Nenhuma imagem bloqueada.",
  },
  emptyTitle: "Nada por aqui",
  kind: {
    original: "Foto original",
    licensed: "Licenciada",
    illustrative: "Ilustrativa",
    ai_generated: "Gerada por IA",
    reproduction: "Reprodução",
  } as Record<string, string>,
  status: { pending: "Pendente", approved: "Aprovada", blocked: "Bloqueada" } as Record<
    string,
    string
  >,
  risk: { baixo: "Risco baixo", medio: "Risco médio", alto: "Risco alto" } as Record<
    string,
    string
  >,
  noPreview: "Prévia indisponível",
  open: (credit: string) => `Abrir imagem: ${credit}`,
  approvalTitle: "Aprovação de imagem",
  details: "Origem e direitos",
  field: {
    kind: "Tipo",
    credit: "Crédito",
    license: "Licença",
    licenseUntil: "Vigência",
    source: "Fonte",
    page: "Página de origem",
    risk: "Risco",
    captured: "Coletada em",
    size: "Tamanho",
    allowedUse: "Uso permitido",
    provenance: "Proveniência",
    removal: "Motivo do bloqueio",
    rights: "Direitos",
    usageScope: "Usos permitidos",
    disclaimer: "Aviso exibido",
  },
  /** Media Registry (D-02): status de direitos, explícito e sem ambiguidade. */
  rights: {
    authorized: "Autorizada (própria ou com acordo)",
    licensed: "Licença identificada",
    unknown: "Direitos desconhecidos: reprodução web, sem autorização registrada",
    pending: "Direitos em apuração",
    expired: "Autorização vencida: não reutilizar",
    blocked: "Bloqueada: não reutilizar",
  } as Record<string, string>,
  usageScope: { editorial: "matéria", social: "redes sociais", thumbnail: "miniatura" } as Record<
    string,
    string
  >,
  noUntil: "Sem vencimento",
  expired: "Vencida",
  usedIn: "Usada em",
  notUsed: "Nenhuma matéria usa esta imagem.",
  approve: "Aprovar imagem",
  block: "Bloquear imagem",
  blockReason: "Motivo do bloqueio",
  blockReasonHint: "Ex.: licença vencida; pedido de remoção do veículo",
  reasonRequired: "Escreva o motivo do bloqueio",
  confirm: "Confirmar",
  cancel: "Cancelar",
  approved: "Imagem aprovada",
  blocked: "Imagem bloqueada e retirada das matérias públicas",
  replace: "Trocar imagem",
  replaceFor: (title: string) => `Trocar a imagem de "${title}"`,
  replaceWith: "Nova imagem",
  replaced: "Imagem trocada",
  replaceInvalid: "Escolha uma imagem aprovada e com licença válida.",
  approveBlocked:
    "Imagem bloqueada não volta ao portal. Se o bloqueio foi engano, cadastre a imagem de novo.",
  approveExpired: "Licença vencida: renove a licença antes de aprovar.",
  takedown: "Remover a pedido do veículo",
  takedownReason: "Pedido do veículo",
  takedownHint: "Ex.: e-mail do veículo de 28/09 pedindo a remoção. A cópia é apagada.",
  takedownAll: "Remover todas as reproduções deste veículo (opt-out)",
  takedownDone: "Reprodução removida: cópia apagada e matérias atualizadas",
  takedownOnlyReproduction: "Remoção a pedido vale só para reprodução de veículo.",
  notFound: "Imagem não encontrada",
  back: "Voltar para a biblioteca",
  licensesTitle: "Direitos e licenças",
  licensesIntro:
    "Licenças de banco de imagens e contratos, com alerta 30 dias antes do vencimento.",
  licensesCaption: "Licenças",
  col: {
    license: "Banco ou contrato",
    until: "Vigência",
    images: "Imagens cobertas",
    alert: "Alerta",
    actions: "Ações",
  },
  expiresIn: (n: number) =>
    n === 0 ? "Vence hoje" : n === 1 ? "Vence em 1 dia" : `Vence em ${n} dias`,
  expiredAgo: (n: number) => (n === 1 ? "Vencida há 1 dia" : `Vencida há ${n} dias`),
  valid: "Em dia",
  expiredAlert: (title: string) =>
    `Licença vencida em matéria publicada: "${title}". Troque a imagem.`,
  alertsTitle: "Alertas",
  renew: "Renovar",
  renewUntil: "Nova vigência",
  renewed: "Licença renovada",
  blockExpired: "Bloquear vencidas",
  blockedExpired: (n: number) => (n === 1 ? "1 imagem bloqueada" : `${n} imagens bloqueadas`),
  agreementsTitle: "Acordos por fonte",
  agreementsCaption: "Acordos de imagem por fonte",
  agreementCol: { source: "Fonte", policy: "Política de imagem", until: "Acordo até" },
  policy: {
    none: "Sem imagem",
    with_agreement: "Com acordo",
    licensed_only: "Só licenciada",
    reproduction: "Reprodução",
  } as Record<string, string>,
  noAgreement: "Sem acordo registrado",
  noLicenses: "Nenhuma imagem licenciada no acervo.",
  generate: "Gerar ilustração",
  generateTitle: "Geração de imagem",
  restrictionsTitle: "Restrições fixas",
  restrictions: [
    "Não fotorrealista",
    "Sem pessoas reais identificáveis",
    "Sem crime, tragédia ou saúde individual",
    "Rótulo IMAGEM GERADA POR IA",
  ],
  suggest: "Sugerir descrição a partir da matéria",
  suggestedPrompt: "Descrição sugerida",
  suggestedAlt: "Texto alternativo sugerido",
  generateOptions: "Gerar 3 opções",
  illustrationForbidden:
    "Ilustração gerada não é permitida para Segurança, crime, tragédia ou saúde individual.",
  generatorUnavailable:
    "Gerador de imagem indisponível neste ambiente. A descrição sugerida pode ir para um ilustrador.",
  aiUnavailable: "A IA não respondeu. Tente de novo em instantes.",
  label: "O rótulo IMAGEM GERADA POR IA entra automaticamente.",
  close: "Fechar",
} as const;

export const MODERATION_TEXT = {
  submissionsTitle: "Sugestões de evento",
  submissionsIntro: "Eventos enviados por leitores. Revise os dados, escolha a categoria e aprove.",
  submissionsCaption: "Sugestões de evento pendentes",
  noSubmissions: "Nenhuma sugestão de evento pendente.",
  emptyTitle: "Nada por aqui",
  sentAt: "Enviada",
  contact: "Contato",
  price: "Preço",
  free: "Grátis",
  age: "Classificação",
  link: "Link",
  fields: {
    title: "Nome do evento",
    startsAt: "Início (fuso de Cuiabá)",
    venue: "Local",
    category: "Categoria",
    description: "Descrição",
  },
  approve: "Aprovar",
  reject: "Rejeitar",
  rejectTitle: "Rejeitar sugestão",
  reasonLabel: "Motivo (enviado ao remetente)",
  reasonHint: "Ex.: o evento é pago e fora de Cuiabá e Várzea Grande",
  reasonRequired: "Escreva o motivo, que vai para quem sugeriu",
  confirm: "Confirmar",
  cancel: "Cancelar",
  approved: "Sugestão aprovada: evento publicado na agenda",
  rejected: "Sugestão rejeitada: motivo enviado ao remetente",
  alreadyDecided: "Esta sugestão já foi decidida.",
  invalidPayload: "A sugestão está incompleta.",
  invalidDate: "Data ou hora inválida",
  reportsTitle: "Denúncias de leitores",
  reportsIntro: "Informação errada, link quebrado, imagem e direito de resposta. Prazo de 24 h.",
  reportsCaption: "Denúncias abertas",
  noReports: "Nenhuma denúncia aberta.",
  kindLabel: "Tipo",
  kind: {
    wrong_info: "Informação errada",
    broken_link: "Link quebrado",
    image: "Imagem",
    right_of_reply: "Direito de resposta",
    other: "Outro",
  } as Record<string, string>,
  filterAll: "Todos os tipos",
  filterApply: "Filtrar",
  due: "Prazo",
  overdue: "Vencido",
  content: "Conteúdo",
  message: "Mensagem",
  noMessage: "Sem mensagem",
  noContact: "Sem e-mail de contato",
  respond: "Responder",
  responseLabel: "Resposta ao leitor",
  responseHint: "Registrada na denúncia e enviada por e-mail quando houver contato.",
  responseRequired: "Escreva a resposta",
  send: "Enviar resposta",
  answered: "Denúncia respondida e retirada da fila",
  alreadyAnswered: "Esta denúncia já foi respondida.",
  openCorrection: "Abrir correção",
  correctionOpened: "Pedido de correção aberto",
  unknownContent: "Conteúdo não encontrado",
  /** Matéria com 3 denúncias em 24 h (A9): item urgente e banner público até alguém resolver. */
  escalation: {
    title: "Urgente: matéria com várias denúncias",
    intro:
      'Três denúncias em 24 h na mesma matéria. A matéria segue no ar com o aviso "Esta matéria está em revisão" até você encerrar a revisão.',
    caption: "Matérias em revisão por denúncias",
    reports: (n: number) => `${n} denúncias`,
    openedAt: "Aberto em",
    openArticle: "Abrir matéria",
    resolve: "Encerrar revisão",
    resolveNote: "Nota (opcional, fica na auditoria)",
    resolved: "Revisão encerrada: o aviso saiu da matéria",
    alreadyResolved: "Esta revisão já foi encerrada.",
  },
} as const;

/** Situação do assunto (AUT-T7, A10): só no Estúdio; o público não vê nenhum estado. */
export const TOPIC_STATE_STUDIO = {
  label: "Situação do assunto",
  state: {
    em_apuracao: "Em apuração",
    confirmado: "Confirmado",
    corrigido: "Corrigido",
    encerrado: "Encerrado",
  },
  line: (title: string, state: string) => `Assunto: ${title} · Situação: ${state}`,
  auto: "Muda sozinha: confirmado com 2 veículos ou 1 fonte oficial, corrigido ao publicar correção, encerrado depois de 7 dias sem novidade.",
} as const;
