/** Textos reutilizados pelos componentes de src/components. */
export const UI = {
  back: "Voltar",
  close: "Fechar",
  more: "Mais opções",
  seeAll: "Ver tudo",
  filters: "Filtros",
  search: "Buscar",
  searchPlaceholder: "Buscar notícias, fontes ou eventos",
  showPassword: "Mostrar senha",
  photo: "Foto",
  follow: "Seguir",
  following: "Seguindo",
  save: "Salvar",
  saved: "Salvo",
  share: "Compartilhar",
  adjustReading: "Ajustar leitura",
  adjustReadingShort: "Leitura",
  useful: "Útil",
  report: "Informar problema",
  reportShort: "Problema",
  articleActions: "Ações da matéria",
  sourcesCount: (n: number) => (n === 1 ? "1 fonte" : `${n} fontes`),
  readMinutes: (n: number) => `${n} min de leitura`,
  trendUp: "alta",
  trendDown: "queda",
  chartSummary: "Valores do gráfico",
  /** Contagem real de uma lista paginada ("Carregar mais"). */
  showing: (shown: number, total: number) => `Mostrando ${shown} de ${total}`,
  loadMore: "Carregar mais",
  /** Contador de caracteres do `TextArea` com `maxLength` ("12/120"). */
  charCount: (used: number, max: number) => `${used}/${max}`,
  charCountLabel: (used: number, max: number) => `${used} de ${max} caracteres`,
  /** Paginação numerada (`ui/Pagination`). */
  pagination: {
    prev: "Anterior",
    next: "Próxima",
    prevLabel: "Página anterior",
    nextLabel: "Próxima página",
    of: (page: number, total: number) => `Página ${page} de ${total}`,
    page: (page: number) => `Página ${page}`,
  },
} as const;
