/** Textos reutilizados pelos componentes de src/components. */
export const UI = {
  back: "Voltar",
  close: "Fechar",
  more: "Mais opções",
  seeAll: "Ver tudo",
  filters: "Filtros",
  search: "Buscar",
  searchPlaceholder: "Buscar notícias, fontes ou eventos",
  showPassword: "Mostrar senha",
  photo: "Foto",
  follow: "Seguir",
  following: "Seguindo",
  save: "Salvar",
  saved: "Salvo",
  share: "Compartilhar",
  adjustReading: "Ajustar leitura",
  adjustReadingShort: "Leitura",
  useful: "Útil",
  report: "Informar problema",
  reportShort: "Problema",
  articleActions: "Ações da matéria",
  sourcesCount: (n: number) => (n === 1 ? "1 fonte" : `${n} fontes`),
  readMinutes: (n: number) => `${n} min de leitura`,
  trendUp: "alta",
  trendDown: "queda",
  chartSummary: "Valores do gráfico",
  /** Contagem real de uma lista paginada ("Carregar mais"). */
  showing: (shown: number, total: number) => `Mostrando ${shown} de ${total}`,
  loadMore: "Carregar mais",
} as const;
